import type { Attribute, CareerPath, Character, Command, Content, FactionId, GameState, Injury, Jutsu, Mentor, MissionOffer, MissionRank, MissionReport, Origin, Rank, Rival, Scar, Tag, Trait } from '../domain/types';
import { roll } from './rng';
import { simulationEvents } from './events';

const rankIndex: Record<MissionRank, number> = { E: 0, D: 1, C: 2, B: 3, A: 4, S: 5 };
const attributeKeys: Attribute[] = ['ninjutsu', 'taijutsu', 'genjutsu', 'intelligence', 'strength', 'speed', 'stamina', 'handSeals', 'chakraControl', 'willpower'];
const traits: Trait[] = [
  { id: 'neutral', name: 'Neutro', description: 'Sem inclinação inicial; todos os caminhos permanecem abertos.', modifiers: {} },
  { id: 'disciplined', name: 'Disciplinado', description: 'Método e precisão acima de explosão física.', modifiers: { intelligence: 1, handSeals: 1, strength: -1 } },
  { id: 'instinctive', name: 'Instintivo', description: 'Reage antes de racionalizar, com menos refinamento técnico.', modifiers: { speed: 1, taijutsu: 1, intelligence: -1 } },
  { id: 'resilient', name: 'Resiliente', description: 'Aguenta mais pressão, mas não é naturalmente veloz.', modifiers: { stamina: 2, speed: -1 } },
  { id: 'precise', name: 'Preciso', description: 'Chakra e genjutsu refinados, à custa de força bruta.', modifiers: { chakraControl: 1, genjutsu: 1, strength: -1 } },
  { id: 'fierce', name: 'Feroz', description: 'Força e vontade intensas, com selos menos naturais.', modifiers: { strength: 1, willpower: 1, handSeals: -1 } },
  { id: 'contemplative', name: 'Contemplativo', description: 'Excelente leitura mental, mas menos explosivo em ninjutsu.', modifiers: { intelligence: 1, willpower: 1, ninjutsu: -1 } }
];
const mentors: Omit<Mentor, 'name' | 'bond' | 'lessons'>[] = [
  { id: 'sena', doctrine: 'guardian', description: 'Ensina que uma linha protegida vale mais que uma vitória chamativa.' },
  { id: 'rei', doctrine: 'pathfinder', description: 'Ensina a ler o caminho que ninguém pensou em usar.' },
  { id: 'kaito', doctrine: 'seal-mentor', description: 'Ensina que toda técnica forte começa com uma condição bem entendida.' },
  { id: 'nari', doctrine: 'vanguard-mentor', description: 'Ensina a assumir o risco que abre uma janela para a equipe.' },
  { id: 'aya', doctrine: 'field-healer', description: 'Ensina que resgate, triagem e ritmo também vencem operações.' }
];
const origins: Origin[] = [
  { academyMemory: 'arquivo inundado', latentTag: 'perception', description: 'Na Academia, você salvou cadernos de um arquivo inundado e aprendeu a ler o que quase se perdeu.' },
  { academyMemory: 'telhado da torre de sinais', latentTag: 'mobility', description: 'Você passou noites na torre de sinais, aprendendo rotas pelo vento e pelo risco.' },
  { academyMemory: 'oficina de selos', latentTag: 'control', description: 'Uma oficina de selos improvisada ensinou que pequenas condições podem mudar uma operação inteira.' },
  { academyMemory: 'enfermaria de treino', latentTag: 'support', description: 'Após um acidente de treino, você entendeu o valor de manter alguém em campo.' },
  { academyMemory: 'pátio silencioso', latentTag: 'stealth', description: 'Você era capaz de atravessar o pátio após o toque de recolher sem acordar um único vigia.' }
];
const rivalBlueprints: Omit<Rival, 'name' | 'rank' | 'reputation' | 'rivalry' | 'stage' | 'stance' | 'lastEncounterDay' | 'studiedStages' | 'memory'>[] = [
  { style: 'corte de vento e avanço', affinity: 'Vento', preferredTag: 'mobility' },
  { style: 'armadilhas de selo e contra-jogo', affinity: 'Selamento', preferredTag: 'control' },
  { style: 'reflexos de gelo e leitura fria', affinity: 'Gelo', preferredTag: 'perception' },
  { style: 'pressão de ferro e guarda curta', affinity: 'Metal', preferredTag: 'defense' },
  { style: 'genjutsu de espelhos e fuga', affinity: 'Miragem', preferredTag: 'stealth' }
];
const defaultJutsu = ['binding-wire', 'scouts-eye', 'stone-guard', 'mist-step', 'warding-palm'];
function defaultFactions() {
  return [
    { id: 'eclipse-covenant' as const, name: 'Pacto do Eclipse', agenda: 'reunir poderes raros antes que as vilas possam controlá-los', standing: 0, heat: 0 },
    { id: 'red-hands' as const, name: 'Mãos Rubras', agenda: 'lucrar com crises de fronteira e contratos que ninguém quer assinar', standing: 0, heat: 0 },
    { id: 'hunter-directorate' as const, name: 'Diretoria de Caçadores', agenda: 'registrar, perseguir ou cooptar shinobi que escapam às vilas', standing: 0, heat: 0 },
    { id: 'ashen-lotus' as const, name: 'Lótus Cinzento', agenda: 'proteger civis e dissidentes que as grandes facções tratam como dano colateral', standing: 0, heat: 0 }
  ];
}
export function loadoutSlots(rank: Rank): number { return rank === 'Genin' ? 3 : rank === 'Chuunin' ? 4 : rank === 'Jounin' ? 5 : 0; }
function fillLoadout(loadout: string[], slots: number): string[] { return [...loadout, ...defaultJutsu.filter(id => !loadout.includes(id))].slice(0, slots); }
function initialProfile(seed: number): [Record<Attribute, number>, Trait, number] { let rng = seed; const attributes = Object.fromEntries(attributeKeys.map(key => [key, 3])) as Record<Attribute, number>; for (let i = 0; i < 3; i++) { let index: number; [index, rng] = roll(rng, attributeKeys.length); const key = attributeKeys[index]; attributes[key] = Math.min(5, attributes[key] + 1); } let traitIndex: number; [traitIndex, rng] = roll(rng, traits.length); const trait = traits[traitIndex]; for (const [key, delta] of Object.entries(trait.modifiers) as [Attribute, number][]) attributes[key] = Math.max(2, Math.min(5, attributes[key] + delta)); return [attributes, trait, rng]; }
function shinobiName(rngState: number): [string, number] { const roots = ['Aki', 'Hina', 'Kyo', 'Mio', 'Riku', 'Suzu', 'Taka', 'Yori', 'Fuyu', 'Nao', 'Kane', 'Shio', 'Rin', 'Tsuki']; const endings = ['ra', 'to', 'mi', 'ya', 'ko', 'shi', 'nori', 'ka', 'zen', 'ma']; let first: number, last: number, rng: number; [first, rng] = roll(rngState, roots.length); [last, rng] = roll(rng, endings.length); return [`${roots[first]}${endings[last]}`, rng]; }
function originProfile(rngState: number): [Origin, Mentor, number] { let originIndex: number, mentorIndex: number, rng: number; [originIndex, rng] = roll(rngState, origins.length); [mentorIndex, rng] = roll(rng, mentors.length); const [name, nextRng] = shinobiName(rng); return [origins[originIndex], { ...mentors[mentorIndex], name, bond: 12, lessons: 0 }, nextRng]; }
function rivalProfile(rngState: number): [Rival, number] { let index: number, rng: number; [index, rng] = roll(rngState, rivalBlueprints.length); const blueprint = rivalBlueprints[index]; const [name, nextRng] = shinobiName(rng); return [{ ...blueprint, name, rank: 'Academy', reputation: 1, rivalry: 12, stage: 0, stance: 'competitive', lastEncounterDay: -99, studiedStages: [], memory: 'transforma cada encontro em uma medida do próprio valor' }, nextRng]; }
const note = (s: GameState, type: string, text: string): GameState => { const event = { day: s.character.day, type, text }; simulationEvents.publish(event); return { ...s, chronicle: [...s.chronicle, event] }; };
const days = (s: GameState, count: number): GameState => {
  const injury = s.character.injury ? { ...s.character.injury, days: Math.max(0, s.character.injury.days - count) } : undefined;
  const healedScar = injury && !injury.days && injury.severity >= 2 ? injury.scar : undefined;
  const scars = healedScar && !s.character.scars.some(scar => scar.id === healedScar.id) ? [...s.character.scars, healedScar] : s.character.scars;
  return { ...s, stats: { ...s.stats, daysServed: s.stats.daysServed + count }, character: { ...s.character, day: s.character.day + count, chakraPool: Math.min(s.character.attributes.stamina * 10 + s.character.attributes.chakraControl * 2, s.character.chakraPool + count * 2), fatigue: Math.max(0, s.character.fatigue - Math.floor(count / 2)), dojutsuStrain: Math.max(0, s.character.dojutsuStrain - Math.floor(count / 3)), scars, injury: injury?.days ? injury : undefined } };
};
export function createGame(name: string, seed = 1337): GameState {
  const stats = { missions: 0, successes: 0, partials: 0, failures: 0, trainings: 0, relationshipsDeepened: 0, ryoEarned: 0, daysServed: 0, highestMission: 'E' as MissionRank };
  const [attributes, trait, profileRng] = initialProfile(seed); const [origin, mentor, mentorRng] = originProfile(profileRng); const [rival, rivalRng] = rivalProfile(mentorRng); const [medicName, medicRng] = shinobiName(rivalRng); const [scoutName, rngState] = shinobiName(medicRng);
  const state: GameState = { saveVersion: 1, seed, stats, rngState, rival, world: { season: 1, borderTension: 2, councilTrust: 0, rumors: ['Mercadores evitam a ponte de Reed Crossing.'], secrets: [], storyFlags: [], factions: defaultFactions(), careerCrisis: { defeatStreak: 0 } }, npcs: [{ id: 'toma', name: 'Toma', role: 'medic', bond: 10, status: 'available', goal: 'provar que suporte também decide batalhas', memory: 'deixou uma anotação de primeiros socorros no seu caderno', arcStage: 0 }, { id: 'mira', name: 'Mira', role: 'scout', bond: 3, status: 'available', goal: 'mapear rotas que ninguém patrulha', memory: 'observa antes de confiar', arcStage: 0 }, { id: 'kaede', name: 'Kaede', role: 'rival', bond: -8, status: 'available', goal: 'superar cada expectativa da família', memory: 'transforma reconhecimento em competição', arcStage: 0 }], team: { memberIds: ['toma'], cohesion: 10 }, character: { name: name || 'Ren', village: 'Hoshigakure', rank: 'Academy', day: 1, attributes, trait, origin, mentor, chakraPool: attributes.stamina * 10 + attributes.chakraControl * 2, fatigue: 0, health: 100, ryo: 30, inventory: { antidote: 0, 'sealing-slate': 0 }, research: { sealing: 0 }, modes: { sageInsight: 0, sageActive: false, sageForms: [], gateTraining: 0, openGates: 0 }, reputation: 0, notoriety: 0, honor: 0, factionTrust: { village: 0, underworld: 0 }, relationships: [{ id: 'sensei', name: mentor.name, bond: mentor.bond, memory: mentor.description }, { id: 'rival', name: rival.name, bond: -8, memory: 'competes for every small recognition' }, { id: 'teammate', name: 'Toma', bond: 8, memory: 'shares quiet notes after class' }], dojutsuActive: false, dojutsuStrain: 0, dojutsuStage: 0, dojutsuInsight: 0, scars: [], knownJutsu: defaultJutsu.slice(0, 3), loadout: defaultJutsu.slice(0, 3), mastery: { 'binding-wire': 1, 'scouts-eye': 1, 'stone-guard': 1 } }, chronicle: [] };
  state.npcs[0].name = medicName; state.npcs[1].name = scoutName; state.npcs[2].name = rival.name;
  state.character.relationships.find(relationship => relationship.id === 'teammate')!.name = medicName;
  return note(state, 'life', `${state.character.name} enters the Academy of ${state.character.village}.`);
}
function technique(content: Content, id: string): Jutsu { const found = content.jutsu.find(j => j.id === id); if (!found) throw new Error(`Unknown jutsu ${id}`); return found; }
function bloodlineFieldRule(id: string | undefined, equipped: number, plan: string | undefined, decision: string | undefined, prepared: Set<string>): { advantage: number; pressure: number; text: string } {
  if (!id || !equipped) return { advantage: 0, pressure: 0, text: '' };
  const rules: Record<string, { advantage: number; pressure: number; text: string }> = {
    'wood-release': { advantage: plan === 'contain' || plan === 'guard' ? 2 : 0, pressure: decision === 'protect' ? -1 : 0, text: 'Mokuton reivindica o terreno: cobertura e rotas vivas alteram a crise.' },
    'ice-release': { advantage: plan === 'infiltrate' ? 2 : 1, pressure: decision === 'pursue' ? -1 : 0, text: 'Hyoton lê frio, reflexo e passagem: o espaço deixa de pertencer só ao perseguidor.' },
    'crystal-release': { advantage: plan === 'guard' || plan === 'contain' ? 2 : 0, pressure: prepared.has('gear') ? -1 : 0, text: 'Shoton refrata linhas de visão e converte cobertura em decisão.' },
    'yin-yang-release': { advantage: decision === 'negotiate' || prepared.has('seal') ? 2 : 1, pressure: decision === 'protect' ? -1 : 0, text: 'Yin–Yang percebe forma e intenção: estabilizar uma relação vira uma resposta de campo.' },
    'sand-style': { advantage: plan === 'contain' || plan === 'guard' ? 2 : 0, pressure: decision === 'protect' ? -1 : 0, text: 'Areia permanece no terreno: passos repetidos passam a denunciar rotas e aberturas.' },
    'magnet-release': { advantage: decision === 'pursue' || prepared.has('gear') ? 2 : 0, pressure: 0, text: 'Magnetismo transforma ferramentas, armaduras e marcas em linhas que podem ser puxadas ou desviadas.' },
    'lava-release': { advantage: plan === 'pressure' ? 2 : 1, pressure: 1, text: 'Lava fecha espaço de forma irreversível: você ganha iniciativa, mas todos pagam pelo terreno perdido.' },
    'boil-release': { advantage: plan === 'infiltrate' ? 2 : 0, pressure: decision === 'protect' ? -1 : 0, text: 'Fervura dissolve visão e posição: aproximações ficam caras sem fingir que o risco desaparece.' },
    'scorch-release': { advantage: plan === 'pressure' || decision === 'pursue' ? 2 : 0, pressure: 1, text: 'Calor seca recursos e cobertura: o inimigo cede espaço, mas o campo se torna mais cruel.' },
    'storm-release': { advantage: plan === 'infiltrate' || decision === 'pursue' ? 2 : 0, pressure: 0, text: 'Tempestade liga leitura, mira e deslocamento em uma rede de respostas rápidas.' },
    'explosion-release': { advantage: plan === 'pressure' ? 2 : 0, pressure: 1, text: 'Explosão rompe formações e cobertura, mas deixa uma crise maior para quem vier depois.' },
    'metal-release': { advantage: plan === 'guard' || plan === 'contain' ? 2 : 0, pressure: prepared.has('gear') ? -1 : 0, text: 'Metal transforma equipamento e cobertura em uma fortificação móvel, não em dano grátis.' },
    'fire-style': { advantage: plan === 'pressure' ? 2 : 0, pressure: 1, text: 'Fogo decide rotas pela ameaça de propagação: pressão aumenta para os dois lados.' },
    'water-style': { advantage: plan === 'contain' || decision === 'protect' ? 1 : 0, pressure: -1, text: 'Água desloca, protege e devolve caminhos de retirada ao campo.' },
    'wind-style': { advantage: plan === 'infiltrate' || decision === 'pursue' ? 2 : 0, pressure: 0, text: 'Vento corta ângulos e transforma mobilidade em uma rota ofensiva.' },
    'earth-style': { advantage: plan === 'guard' || plan === 'contain' ? 2 : 0, pressure: 0, text: 'Terra escolhe onde o combate pode existir e onde uma retirada ainda é possível.' },
    'lightning-style': { advantage: plan === 'pressure' || decision === 'pursue' ? 2 : 0, pressure: 0, text: 'Raio converte tempo de reação em iniciativa; hesitar passa a custar mais.' }
  };
  return rules[id] ?? { advantage: 0, pressure: 0, text: '' };
}
function tagsFor(content: Content, state: GameState): Set<Tag> {
  const tags = new Set(state.character.loadout.flatMap(id => technique(content, id).tags));
  tags.add(state.character.origin.latentTag);
  const bloodlineJutsu = state.character.loadout.filter(id => technique(content, id).bloodline === state.character.bloodline).length;
  if (state.character.specialization === 'tracker') tags.add('perception');
  if (state.character.specialization === 'field-medic') tags.add('support');
  if (state.character.specialization === 'sealwright') tags.add('control');
  if (state.character.specialization === 'vanguard') { tags.add('offense'); tags.add('mobility'); }
  if (state.character.specialization === 'shadow-runner') { tags.add('stealth'); tags.add('mobility'); }
  if (state.character.specialization === 'tactician') { tags.add('control'); tags.add('support'); }
  if (state.character.specialization === 'ironhand') { tags.add('offense'); tags.add('defense'); }
  if (state.character.specialization === 'mirage-weaver') { tags.add('perception'); tags.add('stealth'); }
  if (bloodlineJutsu) {
    if (['wood-release', 'sand-style', 'earth-style', 'metal-release'].includes(state.character.bloodline ?? '')) { tags.add('control'); tags.add('defense'); }
    if (['ice-release', 'storm-release', 'wind-style', 'lightning-style'].includes(state.character.bloodline ?? '')) { tags.add('mobility'); tags.add('perception'); }
    if (['crystal-release', 'magnet-release'].includes(state.character.bloodline ?? '')) { tags.add('defense'); tags.add('perception'); }
    if (['yin-yang-release', 'water-style', 'boil-release'].includes(state.character.bloodline ?? '')) { tags.add('support'); tags.add('control'); }
    if (['lava-release', 'scorch-release', 'explosion-release', 'fire-style'].includes(state.character.bloodline ?? '')) { tags.add('offense'); tags.add('control'); }
  }
  if (state.character.modes.sageActive) { if (state.character.modes.sageForm === 'stone') { tags.add('defense'); tags.add('control'); } if (state.character.modes.sageForm === 'storm') { tags.add('mobility'); tags.add('perception'); } if (state.character.modes.sageForm === 'veil') { tags.add('stealth'); tags.add('perception'); } }
  if (state.character.dojutsuActive) { if (state.character.bloodline === 'lumen-eye') tags.add('support'); else if (['ashen-eye', 'lava-release', 'scorch-release', 'explosion-release', 'fire-style'].includes(state.character.bloodline ?? '')) tags.add('offense'); else if (['wood-release', 'sand-style', 'earth-style', 'metal-release'].includes(state.character.bloodline ?? '')) { tags.add('defense'); tags.add('control'); } else if (['ice-release', 'storm-release', 'wind-style', 'lightning-style'].includes(state.character.bloodline ?? '')) { tags.add('mobility'); tags.add('control'); } else if (['crystal-release', 'magnet-release'].includes(state.character.bloodline ?? '')) { tags.add('defense'); tags.add('perception'); } else if (['yin-yang-release', 'water-style', 'boil-release'].includes(state.character.bloodline ?? '')) { tags.add('support'); tags.add('perception'); } else tags.add('perception'); }
  if (state.character.careerPath === 'anbu' || state.character.careerPath === 'rogue') tags.add('stealth');
  if (state.character.careerPath === 'sensei') tags.add('support');
  if (state.character.careerPath === 'commander') tags.add('control');
  return tags;
}
function missionRank(character: Character, stats: GameState['stats']): MissionRank { if (character.rank === 'Genin') return 'D'; if (character.rank === 'Chuunin') return stats.successes >= 6 ? 'B' : 'C'; if (character.rank === 'Jounin') return character.careerPath && stats.successes >= 16 ? 'S' : stats.successes >= 14 ? 'A' : 'B'; return 'E'; }
const offers: Record<MissionRank, [string, string, string, number, string][]> = {
  E: [['Garden watch', 'Keep boars from the western terraces.', 'A simple household task, with no indicated hostility.', 35, 'E-rank routine duty']],
  D: [['Missing Courier at Reed Crossing', 'Find the courier and recover a sealed medicine case.', 'The dispatcher reports ordinary bandit activity.', 75, 'D-rank: locate a delayed courier'], ['Floodgate Sabotage', 'Protect workers repairing an irrigation gate.', 'A land dispute may have turned personal.', 85, 'D-rank: civilian protection']],
  C: [['Border Lanterns', 'Re-light warning posts and identify the saboteur.', 'Scouts disagree on whether a foreign cell crossed the border.', 155, 'C-rank: hostile territory'], ['Silent Witness', 'Extract a witness before a faction reaches them.', 'The witness may be lying about who is hunting them.', 175, 'C-rank: escort with uncertain loyalty']],
  B: [['Ashen Archive', 'Retrieve a coded ledger from a ruined safehouse.', 'The site was abandoned too cleanly.', 280, 'B-rank: intelligence recovery'], ['River Without Banners', 'Stop armed extortionists without igniting a clan conflict.', 'Local leaders deny involvement; evidence says otherwise.', 310, 'B-rank: political restraint']],
  A: [['The Broken Treaty', 'Prevent a staged attack from becoming open war.', 'Every faction has an incentive to manipulate the report.', 520, 'A-rank: strategic crisis']],
  S: [['The Empty Throne', 'Stop a crisis that can erase the village\'s chain of command.', 'The intelligence is fragmented; the target may be a decoy.', 900, 'S-rank: existential crisis'], ['A Sky of Ash', 'Keep a border evacuation alive while an old weapon turns weather into a battlefield.', 'The opposing force may be fleeing the same disaster.', 940, 'S-rank: civilian catastrophe'], ['The Ninth Ledger', 'Recover proof that can end a clan war, or decide who must never see it.', 'Three villages sent observers under false names.', 980, 'S-rank: political fracture']]
};
const careerOperations: Partial<Record<CareerPath, Partial<Record<MissionRank, [string, string, string, number, string][]>>>> = {
  anbu: { S: [['Veil Without Moon', 'Extract a defector before their identity turns five villages against each other.', 'Your file is deliberately incomplete; even allies are compartmentalized.', 980, 'S-rank ANBU: deniable extraction'], ['The Unwritten Funeral', 'Decide whether an erased operative deserves rescue, proof or silence.', 'Every witness has been instructed to distrust you.', 1020, 'S-rank ANBU: buried truth']] },
  sensei: { S: [['The Last Lesson', 'Evacuate a new class through a collapsing battle line without breaking their will.', 'The safest route is slow; the fast route leaves someone behind.', 880, 'S-rank Sensei: lives before acclaim'], ['Names on the Wall', 'Defend a refuge whose young shinobi refuse to abandon their wounded mentors.', 'Saving everyone may teach the wrong lesson; abandoning them may teach a worse one.', 930, 'S-rank Sensei: inherited responsibility']] },
  commander: { S: [['Seven Bridges', 'Hold a fractured border long enough for diplomacy to become possible.', 'Each bridge saved changes which faction will listen after dawn.', 1020, 'S-rank Command: strategic defense'], ['The Quiet Siege', 'Command a civilian city through a siege without letting its defenders become the threat.', 'Your own officers disagree on what order means.', 1060, 'S-rank Command: authority under strain']] },
  rogue: { B: [['Debt of Cinders', 'Settle an underworld promise while a hunter cell closes in.', 'The client knows your true name and may be bait.', 360, 'B-rank Rogue: hunted contract']], A: [['No Banner at Dawn', 'Break a raid network without giving the village proof of your involvement.', 'The network protects civilians and predators in equal measure.', 610, 'A-rank Rogue: deniable justice']], S: [['The Price of a Name', 'Decide who controls the evidence that could redraw every bounty board.', 'Every side offers a deal; no side offers safety.', 960, 'S-rank Rogue: independent crisis']] }
};
type ArcOffer = { id: string; entry: [string, string, string, number, string] };
const dojutsuArc: Record<string, { name: string; first: [string, string, string]; second: [string, string, string]; final: [string, string, string] }> = {
  'kurogane-eye': {
    name: 'Olho Kurogane',
    first: ['Fios de Intenção', 'Descubra qual decisão move uma célula inimiga antes que ela transforme leitura em emboscada.', 'O adversário sabe que você observa padrões e oferece justamente o padrão mais convincente.'],
    second: ['A Linha que se Move', 'Resolva uma operação em que prever o ataque cedo demais pode condenar a pessoa errada.', 'Seu olho encontra três intenções verdadeiras; somente uma delas explica o campo inteiro.'],
    final: ['O Último Vetor', 'Guie uma crise S-rank sem reduzir pessoas a trajetórias que podem ser calculadas.', 'O inimigo construiu um plano para ser lido. A única variável que não modelou é o que você escolherá proteger.']
  },
  'lumen-eye': {
    name: 'Olho Lumen',
    first: ['Luz sob a Máscara', 'Localize uma mentira que só existe porque todos concordaram em tratá-la como alívio.', 'A visão revela sofrimento demais para uma única resposta conveniente.'],
    second: ['Círculo de Vigília', 'Mantenha aliados conscientes enquanto uma crise tenta transformar percepção em paranoia.', 'Quem pede sua visão pode não suportar a verdade que ela devolve.'],
    final: ['Aurora sem Testemunhas', 'Resolva uma crise S-rank em que revelar tudo pode iniciar guerra e esconder tudo pode repetir o dano.', 'A luz alcança cada lado do conflito; responsabilidade será decidir quem pode carregá-la.']
  },
  'ashen-eye': {
    name: 'Olho Ashen',
    first: ['Cinza que Observa', 'Persiga uma célula que se alimenta do medo de ser vista e transforma reação em combustível.', 'Cada ataque seu pode confirmar a narrativa que o inimigo preparou.'],
    second: ['Fornalha da Memória', 'Recuse uma vitória fácil quando seu poder oferece apagar o rastro e junto dele a responsabilidade.', 'A técnica rival imita sua fúria, mas não pode imitar a escolha de parar.'],
    final: ['Quando a Cinza Escolhe', 'Atravesse uma crise S-rank sem permitir que a necessidade de vencer defina o que seu olho enxerga.', 'O inimigo oferece um alvo impossível de ignorar; o campo exige algo mais difícil que destruição.']
  }
};
function summonArcEntry(id: string, summonName: string, stage: 'first' | 'second' | 'final'): [string, string, string, number, string] {
  const identity: Record<string, [string, string, string]> = {
    'corvid-contract': ['Vigias de Pena', 'seguem uma rede de informantes que só existe enquanto seus segredos não se tornam moeda pública.', 'Os corvos trouxeram uma verdade que pode comprometer a própria fonte.'],
    'hounds-contract': ['A Caçada sem Presa', 'sigam um rastro que termina em inocentes usados para encobrir quem realmente fugiu.', 'Os cães querem resposta direta; o campo exige discriminação.'],
    'moth-contract': ['Luz que Não Denuncia', 'protejam uma rota noturna sem transformar quem busca abrigo em isca visível.', 'As mariposas cobrem o caminho, mas só você decide quem merece saber dele.'],
    'boar-contract': ['Solo Jurado', 'defendam uma comunidade cuja terra é a última peça de um pacto antigo.', 'Os javalis sustentam a linha; permanecer nela terá custo político.'],
    'toad-contract': ['Mapa sob a Água', 'resolvam uma disputa de rotas onde a passagem mais eficiente atravessa uma promessa esquecida.', 'Os sapos conhecem a saída; querem saber o que você fará com quem ficou para trás.']
  };
  const [title, objective, intel] = identity[id] ?? ['Dívida do Contrato', 'honrem uma obrigação que ninguém pode resolver por força.', 'O contrato sabe mais do que contou.'];
  if (stage === 'first') return [`${title}: Primeiro Chamado`, `Com ${summonName}, ${objective}`, intel, 410, 'Contract arc: reciprocal obligation'];
  if (stage === 'second') return [`${title}: Conselho`, `Represente ${summonName} e ${objective}`, `${intel} Agora o contrato avaliará sua decisão, não sua obediência.`, 700, 'Contract arc: earned alliance'];
  return [`${title}: Juramento Final`, `Em uma crise S-rank, ${objective}`, `${intel} O contrato seguirá sua decisão uma vez e lembrará do motivo.`, 1080, 'Contract finale: chosen loyalty'];
}
function personalArc(state: GameState, rank: MissionRank): ArcOffer | undefined {
  const c = state.character, flags = state.world.storyFlags;
  const atLeastB = rankIndex[rank] >= rankIndex.B, atLeastA = rankIndex[rank] >= rankIndex.A, atLeastS = rankIndex[rank] >= rankIndex.S;
  const ocular = c.bloodline ? dojutsuArc[c.bloodline] : undefined;
  if (ocular && c.dojutsuStage >= 1 && c.dojutsuInsight >= 2 && atLeastB && !flags.includes(`dojutsu:${c.bloodline}:first`)) return { id: `dojutsu:${c.bloodline}:first`, entry: [...ocular.first, 440, 'Dōjutsu arc: reading without certainty'] };
  if (ocular && c.dojutsuStage >= 2 && c.dojutsuInsight >= 4 && atLeastA && flags.includes(`dojutsu:${c.bloodline}:first`) && !flags.includes(`dojutsu:${c.bloodline}:second`)) return { id: `dojutsu:${c.bloodline}:second`, entry: [...ocular.second, 740, 'Dōjutsu arc: responsibility of sight'] };
  if (ocular && c.dojutsuStage >= 3 && c.dojutsuInsight >= 6 && atLeastS && flags.includes(`dojutsu:${c.bloodline}:second`) && !flags.includes(`dojutsu:${c.bloodline}:final`)) return { id: `dojutsu:${c.bloodline}:final`, entry: [...ocular.final, 1140, 'Dōjutsu finale: power with restraint'] };
  if (c.bloodline && !ocular && atLeastB && !flags.includes(`affinity:${c.bloodline}:first`)) { const name = c.bloodline; return { id: `affinity:${name}:first`, entry: [`Claim of ${name}`, 'Resolve a crisis where your affinity is feared as much as it is needed.', 'A local leader wants the power contained; survivors need it used.', 430, 'Personal arc: public cost of power'] }; }
  if (c.bloodline && !ocular && atLeastA && flags.includes(`affinity:${c.bloodline}:first`) && !flags.includes(`affinity:${c.bloodline}:second`)) { const name = c.bloodline; return { id: `affinity:${name}:second`, entry: [`The Price of ${name}`, 'Choose what legacy your affinity leaves after an operation no neutral witness can explain.', 'A rival has learned the counter-pattern to your signature techniques.', 720, 'Personal arc: mastery and counterplay'] }; }
  if (c.bloodline && !ocular && atLeastS && flags.includes(`affinity:${c.bloodline}:second`) && !flags.includes(`affinity:${c.bloodline}:final`)) { const name = c.bloodline; return { id: `affinity:${name}:final`, entry: [`Legacy of ${name}`, 'Resolve an S-rank crisis where your affinity can save a region or leave it scarred for a generation.', 'Every faction knows your techniques now; the only unknown is what you refuse to become.', 1120, 'Personal finale: power and legacy'] }; }
  if (c.summon && c.summon.bond >= 4 && atLeastB && !flags.includes(`summon:${c.summon.id}:first`)) return { id: `summon:${c.summon.id}:first`, entry: summonArcEntry(c.summon.id, c.summon.name, 'first') };
  if (c.summon && c.summon.bond >= 7 && atLeastA && flags.includes(`summon:${c.summon.id}:first`) && !flags.includes(`summon:${c.summon.id}:second`)) return { id: `summon:${c.summon.id}:second`, entry: summonArcEntry(c.summon.id, c.summon.name, 'second') };
  if (c.summon && c.summon.bond >= 9 && atLeastS && flags.includes(`summon:${c.summon.id}:second`) && !flags.includes(`summon:${c.summon.id}:final`)) return { id: `summon:${c.summon.id}:final`, entry: summonArcEntry(c.summon.id, c.summon.name, 'final') };
  if (c.bijuu && c.bijuu.trust + c.bijuu.control >= 8 && atLeastB && !flags.includes('bijuu:first')) return { id: 'bijuu:first', entry: ['Voice Beyond the Seal', 'Confront a threat that recognizes the presence behind your seal and tries to provoke it.', 'Your Bijū offers a shortcut. The witnesses will remember how you answer.', 460, 'Bijū arc: control versus relationship'] };
  if (c.bijuu && c.bijuu.synchronization >= 5 && atLeastA && flags.includes('bijuu:first') && !flags.includes('bijuu:second')) return { id: 'bijuu:second', entry: ['A Mantle With Teeth', 'Protect a district while the seal tempts you toward the fastest possible victory.', 'The enemy prepared for your power, not for restraint.', 760, 'Bijū arc: power under observation'] };
  if (c.bijuu && c.bijuu.synchronization >= 8 && atLeastS && flags.includes('bijuu:second') && !flags.includes('bijuu:final')) return { id: 'bijuu:final', entry: ['Two Voices at Dawn', 'Decide whether your sealed partner is weapon, witness or co-author of the final crisis.', 'The village prepared a contingency against you; your Bijū found it first.', 1160, 'Bijū finale: trust and sovereignty'] };
  if (c.modes.sageInsight >= 3 && atLeastB && !flags.includes('sage:first')) return { id: 'sage:first', entry: ['The Natural Silence', 'Meditate through a disaster zone where every movement changes the balance of energy.', 'The calmest path reveals the most dangerous truth.', 420, 'Sage arc: patience under pressure'] };
  if (c.modes.sageForms.length >= 2 && atLeastA && flags.includes('sage:first') && !flags.includes('sage:second')) return { id: 'sage:second', entry: ['Open Sky Doctrine', 'Use two ways of reading nature to resolve a conflict neither can solve alone.', 'The field punishes anyone who mistakes stillness for safety.', 710, 'Sage arc: chosen discipline'] };
  if (c.modes.sageForms.length >= 3 && atLeastS && flags.includes('sage:second') && !flags.includes('sage:final')) return { id: 'sage:final', entry: ['A World That Listens', 'Carry every learned Sage discipline through a catastrophe without letting nature become another weapon of conquest.', 'The quietest answer will cost more than the strongest one.', 1100, 'Sage finale: stewardship'] };
  if (atLeastS && state.rival.stage >= 3 && !flags.includes('rival:final')) return { id: 'rival:final', entry: [`Measure of ${state.rival.name}`, 'Meet your rival at the center of an S-rank crisis where neither career can claim the answer alone.', 'They bring the counter to your signature; you bring the answer to theirs.', 1050, 'Rival finale: rivalry becomes legacy'] };
  return undefined;
}
function missionFaction(state: GameState, rank: MissionRank): FactionId | undefined {
  if (rankIndex[rank] < rankIndex.B) return undefined;
  if (state.world.missingNin) return 'hunter-directorate';
  if (state.character.bijuu || state.character.bloodline) return 'eclipse-covenant';
  if (state.character.careerPath === 'rogue' || state.character.factionTrust.underworld >= 6) return 'red-hands';
  if (state.character.honor >= state.character.notoriety) return 'ashen-lotus';
  return state.world.factions[(state.character.day + rankIndex[rank]) % state.world.factions.length]?.id;
}
function scarFieldRule(character: Character, offer: MissionOffer): { pressure: number; chakra: number; text: string } {
  const relevant = character.scars.filter(scar => scar.fieldCondition === offer.plan || scar.fieldCondition === 'ocular' && character.dojutsuActive || scar.fieldCondition === 'mode' && (character.modes.sageActive || character.modes.openGates > 0));
  if (!relevant.length) return { pressure: 0, chakra: 0, text: '' };
  return { pressure: Math.min(2, relevant.length), chakra: relevant.some(scar => scar.fieldCondition === 'ocular' || scar.fieldCondition === 'mode') ? 3 : 0, text: `${relevant.map(scar => scar.name).join(' e ')} cobra atenção nesta operação; adaptar a resposta importa.` };
}
function offerMission(state: GameState): GameState {
  const rank = missionRank(state.character, state.stats), path = state.character.careerPath, arc = personalArc(state, rank); const pool = path && careerOperations[path]?.[rank] ? careerOperations[path][rank]! : offers[rank]; let rng = state.rngState, pick: number, variance: number; [pick, rng] = roll(rng, pool.length); [variance, rng] = roll(rng, 4);
  const [title, objective, rawIntel, reward, statedRisk] = arc?.entry ?? pool[pick]; const factionId = missionFaction(state, rank); const faction = state.world.factions.find(item => item.id === factionId); const intel = faction ? `${rawIntel} Sinais ligam a crise ao ${faction.name}, que ${faction.agenda}.` : rawIntel; const base = { E: 3, D: 5, C: 8, B: 11, A: 14, S: 18 }[rank];
  const dilemma = rank === 'D' ? 'O courier pode estar ferido; seguir os rastros pode expor civis.' : rank === 'C' ? 'O objetivo e uma testemunha vulnerável se separam no ponto de contato.' : rank === 'S' ? 'Nenhuma escolha preserva tudo: pessoas, segredo e estabilidade política entram em colisão.' : 'A conclusão eficiente pode ferir uma relação política que a vila ainda precisa.';
  const offer: MissionOffer = { id: `${rank}-${state.character.day}-${rng}`, rank, title, objective, intel, statedRisk, dilemma, arcId: arc?.id, factionId, reward: reward + variance * 15, hiddenThreat: base + variance + Number(Boolean(arc)), preparation: [] };
  return note({ ...state, rngState: rng, offer }, 'mission', `Offer ${rank}: ${title}. The briefing includes uncertainty, not certainty.`);
}
function startCombat(state: GameState, content: Content): GameState {
  if (!state.offer || !state.offer.decision || !state.offer.plan) throw new Error('Defina prioridade e plano de campo antes de partir.');
  const o = state.offer, c = state.character, tags = tagsFor(content, state), prep = new Set(o.preparation), teammate = c.relationships.find(r => r.id === 'teammate')!;
  const perception = tags.has('perception'), control = tags.has('control'), defense = tags.has('defense'), offense = tags.has('offense'), stealth = tags.has('stealth'), mobility = tags.has('mobility');
  const fieldTeam = state.npcs.filter(n => state.team.memberIds.includes(n.id) && n.status === 'available'); const bijuu = c.bijuu, modes = c.modes;
  const unstableCloak = Boolean(bijuu?.cloakActive && bijuu.unrest > bijuu.control + bijuu.synchronization);
  const mantle = Boolean(bijuu?.mantleActive); const sageCost = modes.sageForm === 'stone' ? 6 : modes.sageForm === 'storm' ? 10 : modes.sageForm === 'veil' ? 12 : 8; const sageAdvantage = modes.sageForm === 'storm' ? 3 : modes.sageForm === 'stone' ? 2 : modes.sageForm === 'veil' ? 1 : 2;
  const scarRule = scarFieldRule(c, o); const crisisPressure = Math.max(0, state.world.careerCrisis.defeatStreak - 1); const hunterPressure = o.factionId === 'hunter-directorate' && state.world.missingNin ? state.world.missingNin.wantedLevel : 0;
  const kekkeiCount = c.loadout.filter(id => technique(content, id).bloodline === c.bloodline).length;
  const kekkeiRule = bloodlineFieldRule(c.bloodline, kekkeiCount, o.plan, o.decision, prep);
  const planFit = o.plan === 'infiltrate' ? perception || stealth : o.plan === 'contain' ? control || defense : o.plan === 'guard' ? defense || tags.has('support') : offense || mobility;
  const planShift = o.plan === 'infiltrate' ? planFit ? -2 : 1 : o.plan === 'contain' ? planFit ? -1 : 0 : o.plan === 'guard' ? planFit ? -1 : 1 : planFit ? 1 : 0;
  const choicePressure = o.decision === 'protect' ? -1 : o.decision === 'pursue' ? 1 : c.attributes.intelligence >= 5 ? -2 : 1;
  const mentorRule = !prep.has('mentor') ? { advantage: 0, pressure: 0, text: '' } : c.mentor.doctrine === 'guardian' ? { advantage: o.plan === 'guard' || o.plan === 'contain' ? 1 : 0, pressure: -2, text: `${c.mentor.name} antecipou a linha a proteger.` } : c.mentor.doctrine === 'pathfinder' ? { advantage: o.plan === 'infiltrate' ? 2 : 1, pressure: 0, text: `${c.mentor.name} revelou a rota que ninguém anotou.` } : c.mentor.doctrine === 'seal-mentor' ? { advantage: o.plan === 'contain' ? 1 : 0, pressure: -1, text: `${c.mentor.name} identificou a condição que sustentava a armadilha.` } : c.mentor.doctrine === 'vanguard-mentor' ? { advantage: o.plan === 'pressure' ? 2 : 0, pressure: 1, text: `${c.mentor.name} ensinou qual risco abre uma janela real.` } : { advantage: o.decision === 'protect' ? 1 : 0, pressure: -2, text: `${c.mentor.name} delimitou a prioridade de resgate antes do primeiro golpe.` };
  const careerRule = c.careerPath === 'anbu' && (stealth || prep.has('intel')) ? 2 + Number(c.geninFieldMark === 'scout') : c.careerPath === 'sensei' && prep.has('team') ? 2 + Number(c.geninFieldMark === 'guardian') : c.careerPath === 'commander' && o.decision === 'protect' ? 2 + Number(c.geninFieldMark === 'mediator') : c.careerPath === 'rogue' && o.decision === 'negotiate' ? 2 + Number(c.geninFieldMark === 'scout' || c.geninFieldMark === 'mediator') : 0;
  const pressure = o.hiddenThreat + choicePressure + planShift + Math.floor(state.world.borderTension / 3) + crisisPressure + hunterPressure + scarRule.pressure - (perception || prep.has('intel') ? 2 : 0) - (prep.has('gear') ? 1 : 0) - (prep.has('seal') ? 1 + c.research.sealing : 0) - (prep.has('team') && fieldTeam.length && teammate.bond > 10 && state.team.cohesion >= 10 ? 2 : 0) - (prep.has('summon') ? 2 : 0) + kekkeiRule.pressure + mentorRule.pressure;
  const advantage = Math.floor((c.attributes.intelligence + c.attributes.willpower) / 2) - c.fatigue + Math.floor((c.attributes.ninjutsu + c.attributes.taijutsu) / 6) + (c.dojutsuActive ? 1 + c.dojutsuStage : 0) + (c.specialization === 'tracker' ? 1 : 0) + (bijuu?.cloakActive ? (mantle ? 5 : 3) : 0) + (modes.sageActive ? sageAdvantage : 0) + modes.openGates * 2 + careerRule + kekkeiRule.advantage + mentorRule.advantage - (unstableCloak ? 2 : 0);
  const planText = o.plan === 'infiltrate' ? 'Você entra pela lacuna, apostando em informação e silêncio.' : o.plan === 'contain' ? 'Você fecha rotas e tenta controlar o ritmo da crise.' : o.plan === 'guard' ? 'Você ergue uma linha de proteção antes de buscar vitória.' : 'Você força o confronto antes que o inimigo escolha o terreno.';
  const modeText = mantle ? `${bijuu?.name} alcança a Manto Ressonante; poder e inquietação sobem juntos.` : modes.sageActive ? `A disciplina Sage ${modes.sageForm ?? 'instintiva'} molda sua leitura de campo.` : '';
  const opening = { round: 0, success: planFit, text: `${planText} ${planFit ? 'A build responde ao plano escolhido.' : 'O plano pede recursos que sua build não oferece com naturalidade.'} ${kekkeiRule.text} ${mentorRule.text} ${modeText} ${scarRule.text} ${crisisPressure ? 'A maré recente de derrotas torna a equipe e os inimigos menos previsíveis.' : ''} ${hunterPressure ? 'Caçadores conhecem sua assinatura e encurtam suas rotas de fuga.' : ''}` };
  const combat = { plan: o.plan!, round: 0, advantage, pressure, chakra: c.chakraPool + (bijuu?.cloakActive ? (mantle ? 24 : 12) : 0) - (modes.sageActive ? sageCost : 0) - scarRule.chakra, exposure: 0, leadHistory: [], supportUsage: {}, ocularUsed: false, summonUsed: false, steps: [opening] };
  return note({ ...state, combat }, 'combat', `Combate iniciado: plano ${o.plan}. Escolha uma técnica e uma resposta para cada troca.`);
}
function finishMission(state: GameState, outcome: MissionReport['outcome']): GameState {
  if (!state.offer || !state.combat) throw new Error('Combate sem missão ativa.');
  const o = state.offer, c = state.character, combat = state.combat, prep = new Set(o.preparation), bijuu = c.bijuu, modes = c.modes;
  const lastingScar: Scar | undefined = outcome === 'failure' ? modes.openGates > 0 ? { id: 'opened-gates-tissue', name: 'Tecido rompido pelos Portões', adaptation: 'aprendeu a abrir espaço antes de abrir o corpo', fieldCondition: 'pressure' } : c.dojutsuActive ? { id: 'ocular-burn', name: 'Cicatriz ocular', adaptation: 'aprendeu a confiar em leitura parcial quando a visão cobra demais', fieldCondition: 'ocular' } : o.plan === 'pressure' ? { id: 'old-impact', name: 'Impacto mal curado', adaptation: 'aprendeu a escolher ângulos em vez de repetir colisões', fieldCondition: 'pressure' } : { id: 'field-fracture', name: 'Fratura de campo', adaptation: 'aprendeu a defender uma retirada antes de buscar outra vitória', fieldCondition: o.plan ?? 'guard' } : undefined;
  const baseInjury = outcome === 'success' ? undefined : outcome === 'withdrawn' ? { name: 'Retirada sob pressão', severity: combat.exposure > 1 ? 1 : 0, days: 2 + combat.exposure } : { name: outcome === 'partial' ? 'Contusão e exaustão' : 'Ferimento grave em campo', severity: outcome === 'partial' ? 1 + Number(combat.exposure > 1) : 2, days: outcome === 'partial' ? 5 + combat.exposure : 12 + combat.exposure * 2, ...(lastingScar ? { scar: lastingScar } : {}) } as Injury;
  const injury = baseInjury;
  const reward = outcome === 'success' ? o.reward + (o.decision === 'pursue' ? 20 : 0) : outcome === 'partial' ? Math.floor(o.reward * .45) : 0;
  const reputation = (outcome === 'success' ? rankIndex[o.rank] + 1 : outcome === 'partial' ? 0 : outcome === 'withdrawn' ? -1 : -2) + (o.decision === 'protect' && outcome !== 'failure' && outcome !== 'withdrawn' ? 1 : 0);
  const report: MissionReport = { outcome, rank: o.rank, decision: o.decision!, reward, reputation, injury, steps: combat.steps };
  const mastery = { ...c.mastery }; c.loadout.forEach(id => mastery[id] = (mastery[id] ?? 0) + 1);
  const stats = { ...state.stats, missions: state.stats.missions + 1, successes: state.stats.successes + Number(outcome === 'success'), partials: state.stats.partials + Number(outcome === 'partial'), failures: state.stats.failures + Number(outcome === 'failure' || outcome === 'withdrawn'), ryoEarned: state.stats.ryoEarned + reward, highestMission: rankIndex[o.rank] > rankIndex[state.stats.highestMission] ? o.rank : state.stats.highestMission, daysServed: state.stats.daysServed + 3 };
  const team = { ...state.team, cohesion: Math.max(0, Math.min(30, state.team.cohesion + (prep.has('team') && outcome === 'success' ? 2 : outcome === 'failure' ? -2 : 0))), lastMission: o.title };
  const nextBijuu = bijuu ? { ...bijuu, cloakActive: false, mantleActive: false, unrest: Math.max(0, bijuu.unrest + (bijuu.cloakActive ? 1 + Number(bijuu.mantleActive) : 0)), synchronization: Math.min(20, bijuu.synchronization + (bijuu.approach === 'cooperate' && outcome === 'success' ? 1 : 0)) } : undefined;
  const pathHonor = c.careerPath === 'sensei' && o.decision === 'protect' && outcome !== 'failure' && outcome !== 'withdrawn' ? 2 : c.careerPath === 'commander' && o.rank === 'S' && outcome === 'success' ? 2 : 0;
  const pathNotoriety = c.careerPath === 'rogue' && outcome !== 'failure' && outcome !== 'withdrawn' ? 2 : 0;
  const pathSecret = c.careerPath === 'anbu' && o.rank === 'S' && outcome === 'success' ? [`A operação ${o.title} foi apagada dos registros públicos.`] : [];
  const setback = outcome === 'failure' || outcome === 'withdrawn'; const defeatStreak = outcome === 'success' ? Math.max(0, state.world.careerCrisis.defeatStreak - 1) : setback ? state.world.careerCrisis.defeatStreak + 1 : state.world.careerCrisis.defeatStreak;
  const warrant = state.world.careerCrisis.warrant ?? (defeatStreak >= 3 && (c.notoriety >= 5 || Boolean(c.bijuu)) ? 'O conselho abriu um dossiê: mais uma falha pode transformar suspeita em caçada.' : undefined);
  const factions = state.world.factions.map(faction => {
    if (faction.id !== o.factionId) return faction;
    const standing = faction.standing + (outcome === 'success' ? o.decision === 'negotiate' ? 2 : o.decision === 'protect' && faction.id === 'ashen-lotus' ? 3 : -1 : setback ? 1 : 0);
    const heat = Math.max(0, faction.heat + (outcome === 'success' ? 1 : 2) + (state.world.missingNin && faction.id === 'hunter-directorate' ? 1 : 0));
    return { ...faction, standing, heat };
  });
  let next: GameState = { ...state, combat: undefined, world: { ...state.world, borderTension: Math.max(0, state.world.borderTension + (outcome === 'success' ? -1 - (c.careerPath === 'commander' && o.rank === 'S' ? 1 : 0) : 1)), councilTrust: state.world.councilTrust + reputation + (c.careerPath === 'commander' && outcome === 'success' ? 1 : 0), rumors: outcome === 'success' ? [...state.world.rumors.slice(-3), `${o.title} terminou sem virar crise aberta.`] : [...state.world.rumors.slice(-3), `O revés em ${o.title} alimenta dúvidas sobre sua próxima operação.`], secrets: [...state.world.secrets, ...pathSecret], factions, careerCrisis: { defeatStreak, lastSetback: setback ? o.title : state.world.careerCrisis.lastSetback, warrant } }, team, stats, offer: undefined, lastReport: report, character: { ...c, modes: { ...modes, sageActive: false, openGates: 0 }, bijuu: nextBijuu, chakraPool: Math.max(0, Math.min(c.attributes.stamina * 10 + c.attributes.chakraControl * 2, combat.chakra)), day: c.day + 3, fatigue: Math.min(14, c.fatigue + 3 + combat.exposure + (c.dojutsuActive ? 1 : 0) + (bijuu?.cloakActive ? 2 : 0) + (modes.sageActive ? 1 : 0) + modes.openGates * 2), dojutsuStrain: c.dojutsuStrain + (c.dojutsuActive ? 1 : 0), health: Math.max(0, c.health - (injury?.severity ?? 0) * 14 - modes.openGates * 6), ryo: c.ryo + reward, reputation: c.reputation + reputation, honor: c.honor + (outcome === 'success' ? 1 : 0) + (o.decision === 'protect' ? 1 : 0) + pathHonor, notoriety: Math.max(0, c.notoriety + (o.rank === 'B' || o.rank === 'A' || o.rank === 'S' || o.decision === 'pursue' || bijuu?.cloakActive || defeatStreak >= 3 ? 1 : 0) + pathNotoriety), factionTrust: { village: c.factionTrust.village + reputation, underworld: c.factionTrust.underworld + (o.decision === 'negotiate' ? 2 : setback ? 1 : 0) + (c.careerPath === 'rogue' && outcome === 'success' ? 1 : 0) }, injury, mastery } };
  if (o.arcId && outcome === 'success') {
    const arcText = `Arco concluído: ${o.title}. A história dessa escolha permanece na sua crônica.`;
    next = { ...next, world: { ...next.world, storyFlags: [...new Set([...next.world.storyFlags, o.arcId])], secrets: [...next.world.secrets, arcText], rumors: [...next.world.rumors.slice(-3), `${o.title} mudou a forma como a vila fala sobre você.`] }, character: { ...next.character, honor: next.character.honor + 1, reputation: next.character.reputation + 1 } };
  }
  next = note(next, 'mission', `${o.rank}-rank ${o.title}: ${outcome}. ${reward} ryo; confiança da vila ${reputation >= 0 ? '+' : ''}${reputation}.${o.arcId && outcome === 'success' ? ' Arco pessoal avançou.' : ''}`);
  return next.character.health <= 0 ? conclude(next, 'fallen') : next;
}
function resolveCombatBeat(state: GameState, approach: 'probe' | 'commit' | 'protect' | 'feint', jutsuId: string, content: Content): GameState {
  if (!state.combat || !state.offer) throw new Error('Não há combate ativo.');
  const c = state.character, combat = state.combat, round = combat.round + 1; if (round > 3) throw new Error('O combate já foi resolvido.'); if (!c.loadout.includes(jutsuId)) throw new Error('Escolha uma técnica equipada no loadout.'); if (combat.leadHistory.at(-1) === jutsuId && c.loadout.length > 1) throw new Error('Alterne a técnica líder; o restante do loadout precisa entrar na rotação.');
  const jutsu = technique(content, jutsuId); const situationTags: Tag[][] = [['perception', 'stealth', 'defense'], ['control', 'offense', 'defense'], ['mobility', 'control', 'offense', 'support']]; const approachTags: Record<typeof approach, Tag[]> = { probe: ['perception', 'stealth', 'control'], commit: ['offense', 'mobility'], protect: ['defense', 'support', 'control'], feint: ['stealth', 'control', 'mobility'] }; const neededTags = [...situationTags[round - 1], ...approachTags[approach]];
  const support = c.loadout.filter(id => id !== jutsuId).map(id => technique(content, id)).filter(candidate => candidate.tags.some(tag => neededTags.includes(tag))).sort((a, b) => (combat.supportUsage[a.id] ?? 0) - (combat.supportUsage[b.id] ?? 0) || a.id.localeCompare(b.id))[0]; const situationFit = jutsu.tags.some(tag => situationTags[round - 1].includes(tag)); const approachFit = jutsu.tags.some(tag => approachTags[approach].includes(tag));
  const supportCost = support ? Math.ceil(support.chakraCost * 0.45) : 0; const leadAffordable = combat.chakra >= jutsu.chakraCost; const afterLead = leadAffordable ? combat.chakra - jutsu.chakraCost : combat.chakra; const supportAffordable = Boolean(support && leadAffordable && afterLead >= supportCost); const supportFit = Boolean(support?.tags.some(tag => neededTags.includes(tag))); const supportBonus = supportAffordable ? 1 + Number(supportFit) : 0;
  let rng = state.rngState, draw: number; [draw, rng] = roll(rng, 6); const mastery = Math.floor((c.mastery[jutsu.id] ?? 0) / 3); const success = leadAffordable && combat.advantage + draw + mastery + Number(situationFit) + (approachFit ? 2 : 0) + supportBonus >= combat.pressure;
  let advantage = combat.advantage + (success ? 1 : -1), pressure = combat.pressure + (round === 2 ? 1 : 0), exposure = combat.exposure + Number(!success); if (success && approach === 'probe') pressure -= 2; if (success && approach === 'commit') advantage += 2; if (success && approach === 'protect') pressure -= 1; if (success && approach === 'feint') { pressure -= 1; advantage += 1; } if (!success && approach === 'commit') pressure++; const chakra = supportAffordable ? afterLead - supportCost : afterLead;
  const approachText = approach === 'probe' ? 'testa a leitura inimiga' : approach === 'commit' ? 'se compromete com a abertura' : approach === 'protect' ? 'compra tempo e protege a posição' : 'cria uma ameaça falsa para deslocar a resposta'; const supportText = support ? supportAffordable ? ` ${support.name} entra como continuidade, consumindo ${supportCost} de chakra.` : ` ${support.name} teria completado a cadeia, mas não há chakra para sustentá-la.` : ' Nenhuma outra técnica equipada oferece uma continuidade compatível nesta troca.'; const steps = [...combat.steps, { round, success, text: `${jutsu.name}: ${approachText} e ${success ? 'inclina a troca a seu favor' : !leadAffordable ? 'falha por chakra insuficiente' : 'não encontra a resposta necessária'}${approachFit ? '; a função da técnica combina com sua intenção' : '; a técnica não é a resposta mais natural para essa intenção'}.${supportText}` }]; const supportUsage = { ...combat.supportUsage, ...(supportAffordable && support ? { [support.id]: (combat.supportUsage[support.id] ?? 0) + 1 } : {}) }; const nextCombat = { ...combat, round, advantage, pressure, chakra, exposure, leadHistory: [...combat.leadHistory, jutsuId], supportUsage, steps };
  const next = { ...state, rngState: rng, combat: nextCombat }; if (round < 3) return note(next, 'combat', `Troca ${round} resolvida. A crise muda; alterne a técnica líder e escolha a próxima resposta.`); const wins = steps.filter(step => step.round > 0 && step.success).length; return finishMission(next, wins === 3 ? 'success' : wins === 2 ? 'partial' : 'failure');
}
function conclude(state: GameState, ending: 'retired' | 'fallen'): GameState {
  const c = state.character; const title = ending === 'fallen' ? 'Nome lembrado no memorial' : c.careerPath === 'commander' && state.world.councilTrust >= 15 && c.honor >= 20 && state.stats.highestMission === 'S' ? `Kage de ${c.village}` : c.careerPath === 'anbu' ? 'Operador da Sombra' : c.careerPath === 'sensei' ? 'Mestre de uma Nova Geração' : c.careerPath === 'commander' ? 'Comandante de Hoshigakure' : c.careerPath === 'rogue' ? 'Missing-nin de Nome Próprio' : c.rank === 'Jounin' && c.honor >= 12 ? 'Veterano de Hoshigakure' : c.rank === 'Chuunin' ? 'Líder de campo' : 'Vida interrompida cedo';
  const pathText = c.careerPath === 'anbu' ? 'operações que não podiam existir' : c.careerPath === 'sensei' ? 'pessoas que aprendeu a conduzir' : c.careerPath === 'commander' ? 'decisões que sustentaram uma linha inteira' : c.careerPath === 'rogue' ? 'um caminho sem a proteção de uma bandeira' : 'uma carreira sem nomeação final';
  const geninText = c.geninFieldMark === 'guardian' ? 'salvar pessoas no Circuito Regional' : c.geninFieldMark === 'scout' ? 'ler uma rota impossível no Circuito Regional' : c.geninFieldMark === 'mediator' ? 'evitar que rivais transformassem uma prova em conflito' : 'os primeiros passos como Genin';
  const scars = c.scars.length ? `carregou ${c.scars.map(scar => scar.name.toLowerCase()).join(', ')}` : 'saiu sem cicatrizes duradouras'; const exile = state.world.missingNin ? `foi caçado como missing-nin por ${state.world.missingNin.reason}` : 'manteve uma relação pública com a vila';
  const biography = `${c.name} serviu ${state.stats.daysServed} dias, completou ${state.stats.successes}/${state.stats.missions} missões e alcançou ${c.rank}. Veio de ${c.origin.academyMemory}, foi orientado por ${c.mentor.name} e começou por ${geninText}; depois foi marcado por ${pathText}, ${c.relationships.filter(r => r.bond >= 25).map(r => r.name).join(', ') || 'laços ainda em formação'}, ${state.rival.name} como rival ${state.rival.stance}, ${state.world.storyFlags.length} marcos de arco, ${scars}, ${exile}, ${c.honor} honra e ${c.notoriety} notoriedade.`;
  const honors = [state.stats.successes >= 8 ? 'Confiável em Campo' : '', state.stats.highestMission === 'S' ? 'Crise S-rank Enfrentada' : '', state.world.careerCrisis.defeatStreak >= 3 && state.stats.successes > state.stats.failures ? 'Retorno Após a Maré' : '', state.world.storyFlags.some(flag => flag.endsWith(':final') || flag === 'bijuu:final' || flag === 'sage:final' || flag === 'rival:final') ? 'Legado de Arco Concluído' : '', c.relationships.some(r => r.bond >= 35) ? 'Laço que Permanece' : '', c.specialization ? 'Caminho Próprio' : '', c.summon && c.summon.bond >= 5 ? 'Contrato Respeitado' : ''].filter(Boolean);
  const next = { ...state, character: { ...c, rank: ending === 'fallen' ? 'Fallen' as Rank : 'Retired' as Rank }, legacy: { ending, title, biography, honors, stats: state.stats } };
  return note(next, 'legacy', `${c.name}: ${title}. A crônica é preservada para a Hall of Legends.`);
}
function season(state: GameState): GameState {
  let rng = state.rngState, event: number, npcIndex: number; [event, rng] = roll(rng, 9); [npcIndex, rng] = roll(rng, state.npcs.length); let next = days({ ...state, rngState: rng, world: { ...state.world, season: state.world.season + 1 } }, 90); const c = next.character; const npc = next.npcs[npcIndex];
  if (event === 0) { c.factionTrust.village++; next.world.councilTrust++; next.world.factions = next.world.factions.map(faction => faction.id === 'eclipse-covenant' ? { ...faction, heat: faction.heat + 1 } : faction); next.world.rumors.push('Uma delegação pede que Hoshigakure escolha um lado.'); next = note(next, 'world', 'Uma delegação chega à vila; rumores reorientam as prioridades do conselho e o Pacto do Eclipse observa quem pode ser cooptado.'); }
  if (event === 1) { c.factionTrust.underworld++; c.notoriety++; next.world.borderTension += 2; next.world.factions = next.world.factions.map(faction => faction.id === 'red-hands' ? { ...faction, standing: faction.standing + 1, heat: faction.heat + 1 } : faction); next.world.rumors.push('Mercadores relatam soldados sem bandeira na fronteira.'); next = note(next, 'world', 'Mercadores relatam uma rede de contrabando crescendo nas fronteiras; as Mãos Rubras medem quem está disposto a negociar.'); }
  if (event === 2) { c.relationships.find(r => r.id === 'rival')!.bond++; next.rival.rivalry = Math.max(0, next.rival.rivalry - 1); next = note(next, 'relationship', `${next.rival.name} reconhece uma escolha difícil, sem deixar de competir.`); }
  if (event === 3) { c.health = Math.min(100, c.health + 8); next = note(next, 'world', 'Uma estação tranquila permite recuperação e treino silencioso.'); }
  if (event === 4) { npc.status = npc.status === 'available' ? 'deployed' : 'available'; npc.memory = npc.status === 'deployed' ? 'aceitou uma operação própria e não pode responder agora' : 'voltou de uma operação própria com uma história que ainda não contou'; next = note(next, 'npc', `${npc.name} ${npc.status === 'deployed' ? 'partiu para uma missão independente' : 'retornou ao círculo da vila'}.`); }
  if (event === 5) { next.world.borderTension = Math.max(0, next.world.borderTension - 1); c.ryo += 55; next.world.rumors.push('Um mercado itinerante chegou com mapas e equipamentos de regiões distantes.'); next = note(next, 'world', 'Uma feira de rotas reabre comércio, informação e opções de preparação sem exigir uma rotina extra.'); }
  if (event === 6) { c.chakraPool = Math.max(0, c.chakraPool - 12); c.fatigue = Math.min(14, c.fatigue + 2); next.world.borderTension++; next.world.rumors.push('Uma maré de chakra irregular atravessa os vales e desorienta sensores.'); next = note(next, 'world', 'Uma maré de chakra muda o risco das próximas operações: descansar e ler o campo voltam a importar.'); }
  if (event === 7) { if (c.modes.sageInsight > 0) c.modes.sageInsight = Math.min(8, c.modes.sageInsight + 1); else c.honor++; next.world.secrets.push('Um santuário antigo revelou inscrições sobre equilíbrio entre força e território.'); next = note(next, 'world', c.modes.sageInsight > 0 ? 'Um santuário natural aprofunda sua leitura Sage sem transformar meditação em obrigação.' : 'Um santuário natural recompensa contenção e deixa uma pista para futuros caminhos Sage.'); }
  if (event === 8) { c.reputation++; next.world.councilTrust++; next.rival.reputation++; next.world.factions = next.world.factions.map(faction => faction.id === 'ashen-lotus' ? { ...faction, standing: faction.standing + 1 } : faction); next = note(next, 'world', `${next.rival.name} e você aparecem em relatórios opostos sobre uma crise regional; a vila e o Lótus Cinzento passam a acompanhar os dois nomes.`); }
  if (!next.narrative && npc.status === 'available' && npc.arcStage < 2) { next.narrative = { npcId: npc.id, prompt: `${npc.name} pede sua posição sobre ${npc.goal}. O conselho quer uma resposta rápida, mas a verdade é incompleta.`, choices: ['support', 'challenge', 'expose'] }; next = note(next, 'narrative', `Um arco pessoal de ${npc.name} exige uma decisão.`); }
  return next;
}
export function applyCommand(state: GameState, command: Command, content: Content): GameState {
  if (state.legacy) throw new Error('Esta vida terminou. Comece uma nova vida para construir outro legado.');
  let s = structuredClone(state) as GameState; const c = s.character;
  if (command.type === 'TRAIN') { if (c.injury?.severity && (command.attribute === 'strength' || command.attribute === 'taijutsu' || command.attribute === 'speed' || command.attribute === 'stamina')) throw new Error('O ferimento impede treino corporal; recupere-se primeiro.'); c.attributes[command.attribute as Attribute]++; c.fatigue = Math.min(14, c.fatigue + 2); s.stats.trainings++; s = days(s, 1); return note(s, 'training', `${c.name} treina ${command.attribute}; capacidade cresce, mas fadiga cobra espaço.`); }
  if (command.type === 'REST') { s = days(s, 3); s.character.health = Math.min(100, s.character.health + 18); return note(s, 'recovery', 'Três dias de recuperação fazem o corpo avançar no próprio ritmo e restauram foco e tensão ocular.'); }
  if (command.type === 'GRADUATE') { if (c.rank !== 'Academy') throw new Error('A Academia já ficou para trás.'); if (c.attributes.intelligence + c.attributes.handSeals < 8) throw new Error('A prova exige Inteligência + Selos ≥ 8.'); c.rank = 'Genin'; c.loadout = fillLoadout(c.loadout, loadoutSlots(c.rank)); c.knownJutsu = [...new Set([...c.knownJutsu, ...c.loadout])]; s = days(s, 1); return note(s, 'career', `${c.name} se torna Genin. Rank abre o terceiro slot de jutsu; não substitui competência.`); }
  if (command.type === 'START_REGIONAL_CIRCUIT') { if (c.rank !== 'Genin') throw new Error('O Circuito Regional é a primeira prova de campo de um Genin.'); if (c.geninFieldMark) throw new Error('Seu Circuito Regional já deixou uma assinatura de campo.'); if (s.regionalCircuit) throw new Error('O Circuito Regional já está em andamento.'); if (s.stats.successes < 2) throw new Error('O Circuito Regional abre após 2 missões bem-sucedidas.'); s.regionalCircuit = { host: 'Vale das Pontes', prompt: 'Três vilas entram no Circuito Regional. Um desabamento isola uma equipe visitante, um corredor carrega os mapas e mediadores rivais se acusam de sabotagem. Qual frente você assume?', choices: ['shield', 'trace', 'parley'] }; return note(s, 'career', 'Você entra no Circuito Regional do Vale das Pontes: uma prova entre vilas onde combate é só uma das respostas.'); }
  if (command.type === 'RESOLVE_REGIONAL_CIRCUIT') { const circuit = s.regionalCircuit; if (!circuit || c.rank !== 'Genin') throw new Error('Não há Circuito Regional pendente.'); const tags = tagsFor(content, s); const aligned = command.choice === 'shield' ? tags.has('defense') || tags.has('support') || c.attributes.stamina >= 5 : command.choice === 'trace' ? tags.has('perception') || tags.has('mobility') || tags.has('stealth') || c.attributes.speed >= 5 : tags.has('control') || tags.has('support') || c.attributes.intelligence >= 5; s = days(s, 2); const current = s.character; if (command.choice === 'shield') { current.geninFieldMark = 'guardian'; current.honor += 2; current.reputation += 1; } if (command.choice === 'trace') { current.geninFieldMark = 'scout'; current.reputation += 2; current.factionTrust.village += 1; } if (command.choice === 'parley') { current.geninFieldMark = 'mediator'; current.factionTrust.village += 1; current.factionTrust.underworld += 1; s.world.councilTrust += 1; } s.regionalCircuit = undefined; const markText = command.choice === 'shield' ? 'guardião' : command.choice === 'trace' ? 'batedor' : 'mediador'; return note(s, 'career', `No Circuito Regional, você se torna conhecido como ${markText}. ${aligned ? 'Sua build respondeu à crise de forma natural.' : 'Você venceu fora da resposta mais confortável da sua build.'} Isso influencia convites futuros, mas não fecha caminhos.`); }
  if (command.type === 'PROMOTE') { if (c.rank === 'Genin') { if (s.stats.successes < 3 || c.reputation < 4) throw new Error('Chuunin exige 3 sucessos e reputação 4.'); if (!c.geninFieldMark) throw new Error('Antes do Exame Chuunin, participe do Circuito Regional Genin.'); if (s.chuuninExam) throw new Error('O Exame Chuunin já está em andamento; assuma uma prioridade.'); s.chuuninExam = { prompt: 'Na etapa final, um mensageiro ferido, um pergaminho estratégico e um observador inimigo se separam. O que define seu julgamento?', choices: ['rescue', 'secure', 'analyze'] }; return note(s, 'career', 'Exame Chuunin iniciado: sua escolha será registrada, não apenas seu resultado.'); } if (c.rank === 'Chuunin') { if (s.stats.successes < 8 || c.reputation < 12 || Object.values(c.attributes).reduce((a, b) => a + b, 0) < 32) throw new Error('Jounin exige 8 sucessos, reputação 12 e atributos somados em 32.'); c.rank = 'Jounin'; c.loadout = fillLoadout(c.loadout, loadoutSlots(c.rank)); c.knownJutsu = [...new Set([...c.knownJutsu, ...c.loadout])]; return note(s, 'career', 'Promovido a Jounin: o quinto slot de jutsu abre autonomia, não invencibilidade.'); } throw new Error('Não há promoção disponível.'); }
  if (command.type === 'RESOLVE_CHUUNIN_EXAM') { const exam = s.chuuninExam; if (!exam || c.rank !== 'Genin') throw new Error('Não há Exame Chuunin pendente.'); const tags = tagsFor(content, s); const aligned = command.choice === 'rescue' ? tags.has('defense') || tags.has('support') || c.attributes.stamina >= 5 : command.choice === 'secure' ? tags.has('control') || tags.has('mobility') || c.attributes.handSeals >= 5 : tags.has('perception') || c.attributes.genjutsu >= 5 || c.attributes.intelligence >= 5; c.rank = 'Chuunin'; c.loadout = fillLoadout(c.loadout, loadoutSlots(c.rank)); c.knownJutsu = [...new Set([...c.knownJutsu, ...c.loadout])]; s.chuuninExam = undefined; if (command.choice === 'rescue') { c.honor += 2; c.reputation += 1; } if (command.choice === 'secure') { c.reputation += 2; s.world.councilTrust += 1; } if (command.choice === 'analyze') { c.factionTrust.village += 2; s.world.secrets.push('Você identificou o observador que testava o Exame Chuunin.'); } return note(s, 'career', `Você escolhe ${command.choice === 'rescue' ? 'salvar o mensageiro' : command.choice === 'secure' ? 'proteger o pergaminho' : 'ler o observador'}. ${aligned ? 'Sua preparação sustentou a decisão.' : 'A decisão custou mais porque sua build não era a resposta óbvia.'} Você se torna Chuunin e abre o quarto slot de jutsu.`); }
  if (command.type === 'CHOOSE_CAREER_PATH') { if (c.careerPath) throw new Error('A nomeação de carreira já foi assumida nesta vida.'); const bond = c.relationships.find(r => r.id === 'sensei')!.bond + c.relationships.find(r => r.id === 'teammate')!.bond; if (command.path === 'rogue') { const crisisExit = s.world.careerCrisis.defeatStreak >= 3 || s.world.councilTrust <= -3 || Boolean(s.world.careerCrisis.warrant); if (!['Chuunin', 'Jounin'].includes(c.rank) || (c.notoriety < 7 && c.factionTrust.underworld < 7 && !crisisExit)) throw new Error('O caminho missing-nin exige Chuunin e uma ruptura real: notoriedade 7, submundo 7, maré de 3 derrotas ou dossiê do conselho.'); const reason = s.world.careerCrisis.warrant ? 'dossiê do conselho e caçada iminente' : s.world.careerCrisis.defeatStreak >= 3 ? 'uma maré de derrotas que destruiu a confiança formal' : s.world.councilTrust <= -3 ? 'ruptura pública com o conselho' : 'uma escolha consciente por redes paralelas'; c.careerPath = 'rogue'; c.factionTrust.village -= 4; c.notoriety += 3; s.world.missingNin = { reason, wantedLevel: c.notoriety >= 12 ? 3 : c.notoriety >= 8 ? 2 : 1, huntersAlerted: true }; s.world.factions = s.world.factions.map(faction => faction.id === 'hunter-directorate' ? { ...faction, heat: faction.heat + 3 } : faction.id === 'red-hands' ? { ...faction, standing: faction.standing + 2 } : faction); return note(s, 'career', `Você se torna missing-nin por ${reason}. A Diretoria de Caçadores abre a caçada; contratos futuros vêm por redes paralelas e têm outro preço.`); } if (c.rank !== 'Jounin') throw new Error('Nomeações ANBU, Sensei e Comando exigem Jounin.'); if (command.path === 'anbu' && (s.stats.successes < 12 || c.reputation < 16 || c.attributes.intelligence + c.attributes.willpower < 11)) throw new Error('ANBU exige 12 sucessos, reputação 16 e Inteligência + Vontade 11.'); if (command.path === 'sensei' && (s.stats.successes < 10 || c.honor < 10 || bond < 45)) throw new Error('Sensei exige 10 sucessos, honra 10 e vínculos somados 45.'); if (command.path === 'commander' && (s.stats.successes < 12 || c.reputation < 18 || s.world.councilTrust < 8)) throw new Error('Comando exige 12 sucessos, reputação 18 e confiança do conselho 8.'); c.careerPath = command.path; return note(s, 'career', command.path === 'anbu' ? 'Você aceita uma máscara ANBU: informação e silêncio passam a definir suas operações.' : command.path === 'sensei' ? 'Você assume uma turma: sustentar outros se torna parte do seu próprio campo.' : 'Você recebe comando de campo: proteger a linha importa mais que brilho individual.'); }
  if (command.type === 'LEARN_JUTSU') { const slots = loadoutSlots(c.rank); if (!slots) throw new Error('Aprender jutsu exige uma carreira shinobi ativa.'); if (c.knownJutsu.includes(command.id)) throw new Error('Essa técnica já está na sua biblioteca.'); const j = technique(content, command.id); const available: MissionRank = c.rank === 'Genin' ? 'D' : c.rank === 'Chuunin' ? 'B' : 'S'; if (j.minimumRank && rankIndex[j.minimumRank] > rankIndex[available]) throw new Error(`${j.name} exige acesso a missões ${j.minimumRank}-rank.`); const missing = (j.requires ?? []).filter(id => !c.knownJutsu.includes(id)); if (missing.length) throw new Error(`${j.name} exige dominar: ${missing.map(id => technique(content, id).name).join(', ')}.`); if (j.specialization && c.specialization !== j.specialization) throw new Error(`${j.name} exige a especialização ${j.specialization}.`); if (j.bloodline && c.bloodline !== j.bloodline) throw new Error(`${j.name} exige a linhagem ${j.bloodline}.`); const cost = 15 + j.chakraCost * 2 + (j.requires?.length ?? 0) * 10; if (c.ryo < cost) throw new Error(`Aprender ${j.name} exige ${cost} ryo.`); c.ryo -= cost; s = days(s, 2 + (j.requires?.length ?? 0)); s.character.knownJutsu.push(j.id); s.character.mastery[j.id] ??= 0; return note(s, 'jutsu', `${j.name} entra na biblioteca após estudo de uma ramificação. Ainda precisa ser equipado para entrar em campo.`); }
  if (command.type === 'SET_LOADOUT') { const slots = loadoutSlots(c.rank); if (!slots || command.jutsuIds.length !== slots || new Set(command.jutsuIds).size !== slots) throw new Error(`Este rank requer exatamente ${slots} técnicas distintas no loadout.`); const available: MissionRank = c.rank === 'Genin' ? 'D' : c.rank === 'Chuunin' ? 'B' : 'S'; command.jutsuIds.forEach(id => { const j = technique(content, id); if (!c.knownJutsu.includes(id)) throw new Error(`${j.name} ainda não foi aprendida.`); if (j.minimumRank && rankIndex[j.minimumRank] > rankIndex[available]) throw new Error(`${j.name} exige acesso a missões ${j.minimumRank}-rank.`); }); c.loadout = command.jutsuIds; return note(s, 'loadout', `Loadout: ${command.jutsuIds.map(id => technique(content, id).name).join(' + ')}.`); }
  if (command.type === 'CHOOSE_PATH') { if (!['Genin', 'Chuunin', 'Jounin'].includes(c.rank)) throw new Error('Caminhos se abrem após a graduação.'); const list = command.kind === 'specialization' ? content.specializations : command.kind === 'bloodline' ? content.bloodlines : content.summons; const item = list.find(i => i.id === command.id); if (!item) throw new Error('Caminho desconhecido.'); if (command.kind === 'specialization' && c.specialization) throw new Error('A especialização atual já define sua prática; crie outra vida para outro caminho.'); if (command.kind === 'bloodline' && c.bloodline) throw new Error('Uma linhagem ou Kekkei Genkai já foi definida nesta vida.'); if (command.kind === 'summon' && c.summon) throw new Error('Um contrato de invocação já está firmado.'); if (command.kind === 'specialization') c.specialization = command.id; if (command.kind === 'bloodline') c.bloodline = command.id; if (command.kind === 'summon') c.summon = { id: command.id, name: item.name, bond: 1, favor: 0 }; return note(s, 'path', `${c.name} inicia ${item.name}; isso cria uma regra própria, não um bônus percentual.`); }
  if (command.type === 'FORM_BIJUU_LINK') { if (!['Genin', 'Chuunin', 'Jounin'].includes(c.rank)) throw new Error('O selo só pode ser enfrentado após a Academia.'); if (c.bijuu) throw new Error('Este personagem já carrega uma Bijū.'); const bijuu = content.bijuu.find(b => b.id === command.id); if (!bijuu) throw new Error('Bijū desconhecida.'); c.bijuu = { id: bijuu.id, name: bijuu.name, trust: 0, respect: 0, control: 1, synchronization: 0, unrest: 4, cloakActive: false, mantleActive: false }; c.notoriety += 2; return note(s, 'bijuu', `${bijuu.name} desperta atrás do selo. A vila nota que algo mudou.`); }
  if (command.type === 'CULTIVATE_BIJUU') { const b = c.bijuu; if (!b) throw new Error('Não há uma Bijū com quem lidar.'); s = days(s, 4); const current = s.character.bijuu!; current.approach = command.approach; if (command.approach === 'cooperate') { current.trust = Math.min(20, current.trust + 3); current.respect = Math.min(20, current.respect + 1); current.synchronization = Math.min(20, current.synchronization + 1); current.unrest = Math.max(0, current.unrest - 2); } if (command.approach === 'suppress') { current.control = Math.min(20, current.control + 3); current.trust = Math.max(-10, current.trust - 2); current.unrest += 1; } if (command.approach === 'dominate') { if (s.character.attributes.willpower < 5) throw new Error('Dominação exige Willpower 5.'); current.control = Math.min(20, current.control + 1); current.respect = Math.min(20, current.respect + 2); current.trust = Math.max(-10, current.trust - 1); current.unrest += 2; }
    return note(s, 'bijuu', `${command.approach}: trust ${current.trust}, control ${current.control}, sincronização ${current.synchronization}, unrest ${current.unrest}.`); }
  if (command.type === 'TOGGLE_CLOAK') { const b = c.bijuu; if (!b) throw new Error('Não há chakra de Bijū selado.'); if (!b.cloakActive && b.control < 4 && b.synchronization < 3) throw new Error('A capa exige Control 4 ou Sincronização 3.'); if (!b.cloakActive && b.unrest > b.control + b.synchronization + 4) throw new Error('A Bijū está inquieta demais para uma transformação segura.'); b.cloakActive = !b.cloakActive; if (!b.cloakActive) b.mantleActive = false; return note(s, 'bijuu', b.cloakActive ? 'A capa de chakra se forma. Missões ganham poder e risco; ela se desfaz após o campo.' : 'A capa de chakra é recolhida antes de consumir o controle.'); }
  if (command.type === 'TOGGLE_MANTLE') { const b = c.bijuu; if (!b) throw new Error('Não há Bijū selada.'); if (!b.mantleActive && (b.control < 6 || b.synchronization < 5 || b.trust < 4)) throw new Error('Manto Ressonante exige Control 6, Sync 5 e Trust 4.'); if (!b.mantleActive && b.unrest > b.control + b.synchronization + 1) throw new Error('A Bijū está inquieta demais para sustentar o Manto Ressonante.'); b.mantleActive = !b.mantleActive; b.cloakActive = b.mantleActive || b.cloakActive; return note(s, 'bijuu', b.mantleActive ? 'O Manto Ressonante se fecha: mais chakra e pressão, mas inquietação maior após o campo.' : 'O Manto Ressonante recua para uma capa de chakra mais segura.'); }
  if (command.type === 'TOGGLE_DOJUTSU') { if (!c.bloodline) throw new Error('Sem dōjutsu ou Kekkei Genkai desperto.'); if (!c.dojutsuActive && c.dojutsuStrain >= 7) throw new Error('Strain de linhagem alto demais; descanse antes de ativar.'); c.dojutsuActive = !c.dojutsuActive; return note(s, 'bloodline', c.dojutsuActive ? 'A afinidade de linhagem é ativada para o próximo campo, ao custo de strain.' : 'A afinidade de linhagem é desativada para preservar o corpo.'); }
  if (command.type === 'CULTIVATE_DOJUTSU') { if (!c.bloodline) throw new Error('Sem dōjutsu ou Kekkei Genkai desperto.'); if (c.dojutsuStrain > 2) throw new Error('O corpo precisa recuperar antes de aprofundar a linhagem.'); s = days(s, 3); const eye = s.character; eye.dojutsuInsight++; const threshold = (eye.dojutsuStage + 1) * 3; if (eye.dojutsuInsight >= threshold && eye.dojutsuStage < 3) { eye.dojutsuStage++; eye.dojutsuInsight = 0; return note(s, 'bloodline', `${c.bloodline} alcança estágio ${eye.dojutsuStage}: regra de campo mais profunda, mas strain mais perigoso.`); } return note(s, 'bloodline', `Treino de linhagem aprofunda a afinidade (${eye.dojutsuInsight}/${threshold}).`); }
  if (command.type === 'CULTIVATE_SUMMON') { if (!c.summon) throw new Error('Sem contrato de invocação.'); s = days(s, 3); const summon = s.character.summon!; summon.bond = Math.min(12, summon.bond + 1); summon.favor = Math.min(8, summon.favor + (s.character.honor >= 3 ? 2 : 1)); return note(s, 'summon', `${summon.name} aceita uma tarefa fora de combate. Vínculo ${summon.bond}; favor ${summon.favor}.`); }
  if (command.type === 'BUY_SUPPLY') { const price = command.item === 'antidote' ? 18 : 35; if (c.ryo < price) throw new Error('Ryo insuficiente para esse suprimento.'); c.ryo -= price; c.inventory[command.item]++; return note(s, 'logistics', `Comprado: ${command.item}. Estoque agora ${c.inventory[command.item]}.`); }
  if (command.type === 'RESEARCH') { const cost = 45 + c.research[command.project] * 30; if (c.ryo < cost) throw new Error(`Pesquisa exige ${cost} ryo.`); c.ryo -= cost; s = days(s, 5); const research = s.character.research; research[command.project]++; return note(s, 'research', `${command.project} alcança nível ${research[command.project]}; conhecimento muda opções de preparação de missão.`); }
  if (command.type === 'CULTIVATE_SAGE') { if (c.attributes.chakraControl < 5 || c.attributes.intelligence < 5) throw new Error('Sage Mode exige Controle de Chakra 5 e Inteligência 5.'); s = days(s, 4); s.character.modes.sageInsight = Math.min(8, s.character.modes.sageInsight + 1); return note(s, 'sage', `Meditação natural aprofunda o insight (${s.character.modes.sageInsight}/8).`); }
  if (command.type === 'ATTUNE_SAGE_FORM') { const modes = c.modes; const requirement = command.form === 'stone' ? 2 : command.form === 'storm' ? 3 : 5; const name = command.form === 'stone' ? 'Pedra' : command.form === 'storm' ? 'Tempestade' : 'Véu'; if (modes.sageInsight < requirement) throw new Error(`Forma Sage da ${name} exige insight ${requirement}.`); if (!modes.sageForms.includes(command.form)) { s = days(s, 2); s.character.modes.sageForms = [...s.character.modes.sageForms, command.form]; } s.character.modes.sageForm = command.form; return note(s, 'sage', `Forma Sage da ${name} sintonizada: ela muda as tags e o custo da próxima missão.`); }
  if (command.type === 'TOGGLE_SAGE') { const modes = c.modes; if (!modes.sageActive && modes.sageInsight < 3) throw new Error('Sage Mode exige 3 de insight natural.'); if (!modes.sageActive && !modes.sageForm) throw new Error('Escolha uma Forma Sage antes de estabilizar energia natural.'); const cost = modes.sageForm === 'stone' ? 6 : modes.sageForm === 'storm' ? 10 : 12; if (!modes.sageActive && c.chakraPool < cost) throw new Error(`Chakra insuficiente para a Forma Sage (${cost}).`); modes.sageActive = !modes.sageActive; return note(s, 'sage', modes.sageActive ? `Forma Sage ${modes.sageForm} estabilizada para a próxima missão.` : 'A energia natural é dispersada antes de campo.'); }
  if (command.type === 'TRAIN_GATES') { if (c.attributes.strength < 5 || c.attributes.stamina < 5) throw new Error('Treino dos Portões exige Força 5 e Stamina 5.'); s = days(s, 3); s.character.modes.gateTraining = Math.min(6, s.character.modes.gateTraining + 1); s.character.fatigue = Math.min(14, s.character.fatigue + 2); return note(s, 'gates', `Condicionamento dos Portões: ${s.character.modes.gateTraining}/4.`); }
  if (command.type === 'OPEN_GATES') { const modes = c.modes; if (modes.openGates) throw new Error('Um Portão já está aberto.'); if (command.level === 1 && modes.gateTraining < 2) throw new Error('O Primeiro Portão exige treinamento 2.'); if (command.level === 2 && (modes.gateTraining < 4 || c.health < 55)) throw new Error('O Segundo Portão exige treinamento 4 e Saúde 55.'); if (command.level === 3 && (modes.gateTraining < 6 || c.health < 70 || c.attributes.willpower < 5)) throw new Error('O Terceiro Portão exige treinamento 6, Saúde 70 e Willpower 5.'); modes.openGates = command.level; return note(s, 'gates', `${command.level}º Portão aberto para a próxima missão; o preço será cobrado do corpo.`); }
  if (command.type === 'RIVAL_ENCOUNTER') { if (s.offer || s.combat) throw new Error('Encontros com a rival acontecem entre operações.'); const stageByRank: Record<Rank, 0 | 1 | 2 | 3 | 4> = { Academy: 0, Genin: 1, Chuunin: 2, Jounin: 3, Retired: 4, Fallen: 4 }; const stage = stageByRank[c.rank]; const rival = { ...s.rival, rank: c.rank, stage, reputation: Math.max(0, c.reputation + (s.rival.rivalry >= 18 ? 2 : 0)) }; if (c.day - rival.lastEncounterDay < 8) throw new Error(`${rival.name} precisa de tempo antes de transformar outro encontro em disputa.`); if (command.approach === 'challenge') { let rollValue: number, nextRng: number; [rollValue, nextRng] = roll(s.rngState, 6); const tags = tagsFor(content, s); const playerRead = Math.floor((c.attributes.intelligence + c.attributes.willpower + c.attributes.speed) / 3) + (tags.has(rival.preferredTag) ? 4 : 0); const rivalRead = 4 + stage * 2 + rollValue + Math.floor(rival.reputation / 4); const won = playerRead >= rivalRead; s = days(s, 2); s.rngState = nextRng; s.rival = { ...rival, rivalry: Math.max(0, rival.rivalry + (won ? -2 : 3)), stance: won ? 'respectful' : rival.rivalry >= 18 ? 'hostile' : 'competitive', reputation: rival.reputation + Number(!won), lastEncounterDay: s.character.day, memory: won ? 'aceitou que sua leitura de campo foi superada, mas prometeu responder' : 'saiu da disputa com um novo alvo claro para superar' }; s.character.reputation += won ? 1 : 0; s.character.fatigue = Math.min(14, s.character.fatigue + Number(!won)); s.character.relationships.find(r => r.id === 'rival')!.bond += won ? 2 : -2; return note(s, 'rival', won ? `${rival.name} desafia você com ${rival.style}. Sua build encontrou a resposta; respeito cresce, mas a próxima disputa será mais difícil.` : `${rival.name} vence o encontro com ${rival.style}. Ela não rouba sua carreira, mas deixa uma pergunta incômoda sobre sua próxima evolução.`); }
    if (command.approach === 'study') { if (rival.studiedStages.includes(stage)) throw new Error('Você já extraiu a lição possível dessa fase da rivalidade.'); const attribute: Record<Tag, Attribute> = { offense: 'taijutsu', defense: 'stamina', control: 'handSeals', mobility: 'speed', perception: 'intelligence', support: 'chakraControl', stealth: 'genjutsu' }; s = days(s, 2); s.character.attributes[attribute[rival.preferredTag]]++; s.rival = { ...rival, rivalry: Math.max(0, rival.rivalry - 1), stance: 'respectful', lastEncounterDay: s.character.day, studiedStages: [...rival.studiedStages, stage], memory: `você estudou o ${rival.style} sem transformar a diferença em submissão` }; s.character.relationships.find(r => r.id === 'rival')!.bond += 3; return note(s, 'rival', `Você estuda ${rival.name} em vez de tentar vencê-la. ${attribute[rival.preferredTag]} +1; a rivalidade vira referência de desenvolvimento.`); }
    if (rival.rivalry > 16) throw new Error('Uma aliança exige reduzir a rivalidade primeiro — vença com respeito ou estude o contraponto.'); s = days(s, 1); s.rival = { ...rival, stance: 'allied', rivalry: Math.max(0, rival.rivalry - 3), lastEncounterDay: s.character.day, memory: 'aceitou cooperar numa crise sem fingir que a competição desapareceu' }; s.team.cohesion = Math.min(30, s.team.cohesion + 2); s.character.honor++; s.character.relationships.find(r => r.id === 'rival')!.bond += 5; return note(s, 'rival', `${rival.name} aceita uma aliança desconfortável. A rivalidade continua, mas agora pode sustentar uma crise em vez de apenas medi-la.`); }
  if (command.type === 'BUILD_RELATIONSHIP') { const r = c.relationships.find(x => x.id === command.id)!; s = days(s, 3); const updatedBond = Math.min(50, r.bond + (command.id === 'rival' ? 2 : 5)); s.character.relationships.find(x => x.id === command.id)!.bond = updatedBond; if (command.id === 'sensei') s.character.mentor.bond = updatedBond; s.stats.relationshipsDeepened++; return note(s, 'relationship', `${r.name}: ${r.memory}. O vínculo agora é ${updatedBond}.`); }
  if (command.type === 'MENTOR_LESSON') { const mentor = c.mentor; if (mentor.lessons >= 3) throw new Error('Este mentor já compartilhou todas as lições decisivas desta vida.'); const requiredBond = 12 + mentor.lessons * 8; if (mentor.bond < requiredBond) throw new Error(`A próxima lição de ${mentor.name} exige vínculo ${requiredBond}.`); const curriculum: Record<typeof mentor.doctrine, Attribute[]> = { guardian: ['stamina', 'willpower', 'chakraControl'], pathfinder: ['speed', 'intelligence', 'handSeals'], 'seal-mentor': ['handSeals', 'chakraControl', 'intelligence'], 'vanguard-mentor': ['taijutsu', 'strength', 'speed'], 'field-healer': ['chakraControl', 'intelligence', 'willpower'] }; const attribute = curriculum[mentor.doctrine][mentor.lessons]; s = days(s, 2); s.character.mentor.lessons++; s.character.attributes[attribute]++; s.character.mentor.bond = Math.min(50, s.character.mentor.bond + 2); s.character.relationships.find(r => r.id === 'sensei')!.bond = s.character.mentor.bond; return note(s, 'mentor', `${mentor.name} aprofunda a doutrina ${mentor.doctrine}. Lição ${s.character.mentor.lessons}/3: ${attribute} +1 e conselho tático disponível antes de missão.`); }
  if (command.type === 'CONSULT_MENTOR') { const o = s.offer, mentor = c.mentor; if (!o) throw new Error('Consulte o mentor somente diante de uma missão concreta.'); if (mentor.lessons < 1) throw new Error('Uma lição decisiva é necessária antes de pedir conselho de campo.'); if ((o.preparation ?? []).includes('mentor')) throw new Error('O mentor já analisou esta operação.'); o.preparation = [...(o.preparation ?? []), 'mentor']; return note(s, 'mentor', `${mentor.name}: ${mentor.description} O conselho muda a preparação, não substitui sua decisão.`); }
  if (command.type === 'BUILD_NPC_BOND') { const npc = s.npcs.find(x => x.id === command.id); if (!npc) throw new Error('Contato desconhecido.'); if (npc.status !== 'available') throw new Error(`${npc.name} não está disponível nesta estação.`); s = days(s, 3); const updated = s.npcs.find(x => x.id === command.id)!; updated.bond = Math.min(50, updated.bond + (updated.role === 'rival' ? 2 : 5)); updated.memory = `você investiu tempo no objetivo: ${updated.goal}`; s.stats.relationshipsDeepened++; return note(s, 'npc', `${updated.name} compartilha ${updated.goal}; vínculo ${updated.bond}.`); }
  if (command.type === 'TOGGLE_TEAM_MEMBER') { const npc = s.npcs.find(x => x.id === command.id); if (!npc || npc.role === 'rival') throw new Error('Esse contato não pode compor a equipe agora.'); if (npc.status !== 'available' || npc.bond < 8) throw new Error('Convites exigem disponibilidade e vínculo 8.'); const has = s.team.memberIds.includes(npc.id); if (!has && s.team.memberIds.length >= 2) throw new Error('A equipe de campo comporta dois aliados além de você.'); s.team.memberIds = has ? s.team.memberIds.filter(id => id !== npc.id) : [...s.team.memberIds, npc.id]; return note(s, 'team', has ? `${npc.name} deixa a formação de campo.` : `${npc.name} entra na formação de campo.`); }
  if (command.type === 'RESOLVE_NARRATIVE') { const moment = s.narrative; if (!moment) throw new Error('Não há arco narrativo pendente.'); const npc = s.npcs.find(n => n.id === moment.npcId)!; s = days(s, 2); const updated = s.npcs.find(n => n.id === moment.npcId)!; if (command.choice === 'support') { updated.bond = Math.min(50, updated.bond + 5); updated.memory = 'você ofereceu apoio quando a resposta fácil era recuar'; s.team.cohesion = Math.min(30, s.team.cohesion + 1); } if (command.choice === 'challenge') { updated.bond += updated.role === 'rival' ? 3 : -1; updated.memory = 'você contestou a escolha e exigiu uma resposta mais difícil'; s.world.councilTrust++; } if (command.choice === 'expose') { if (s.character.attributes.intelligence < 4) throw new Error('Expor a verdade exige Inteligência 4 para sustentar a investigação.'); updated.bond -= updated.role === 'rival' ? 1 : 3; updated.memory = 'você levou a informação ao conselho, apesar do custo pessoal'; s.world.secrets.push(`A verdade sobre ${updated.goal} foi levada ao conselho.`); s.character.honor++; }
    updated.arcStage++; s.narrative = undefined; return note(s, 'narrative', `${updated.name}: escolha ${command.choice}; o arco pessoal avança para ${updated.arcStage}.`); }
  if (command.type === 'ADVANCE_SEASON') return season(s);
  if (command.type === 'OFFER_MISSION') { if (!['Genin', 'Chuunin', 'Jounin'].includes(c.rank)) throw new Error('Somente shinobi ativos recebem missões.'); if (c.loadout.length !== loadoutSlots(c.rank)) throw new Error(`Complete os ${loadoutSlots(c.rank)} slots de jutsu antes de aceitar missão.`); return offerMission(s); }
  if (command.type === 'PREPARE_SMART') { const o = s.offer; if (!o) throw new Error('Não há oferta para preparar.'); const prepared = new Set(o.preparation); const choices: string[] = []; if (!prepared.has('intel')) { prepared.add('intel'); choices.push('inteligência'); } if (!prepared.has('seal') && c.inventory['sealing-slate'] > 0 && c.research.sealing > 0) { c.inventory['sealing-slate']--; prepared.add('seal'); choices.push('selamento'); } if (!prepared.has('team') && c.relationships.find(r => r.id === 'teammate')!.bond >= 10 && s.team.cohesion >= 10 && s.npcs.some(n => s.team.memberIds.includes(n.id) && n.status === 'available')) { prepared.add('team'); choices.push('equipe'); } o.preparation = [...prepared] as typeof o.preparation; return note(s, 'preparation', choices.length ? `Preparação recomendada aplicada: ${choices.join(', ')}.` : 'Nenhuma preparação adicional era necessária.'); }
  if (command.type === 'PREPARE') { const o = s.offer; if (!o) throw new Error('Não há oferta para preparar.'); if (o.preparation?.includes(command.method)) throw new Error('Essa preparação já foi feita.'); if (command.method === 'gear') { if (c.ryo < 20) throw new Error('Ryo insuficiente para equipamento de campo.'); c.ryo -= 20; } if (command.method === 'seal') { if (!c.inventory['sealing-slate']) throw new Error('Você precisa de uma placa de selamento.'); c.inventory['sealing-slate']--; } if (command.method === 'rest') { s = days(s, 1); s.character.fatigue = Math.max(0, s.character.fatigue - 3); } if (command.method === 'team' && (c.relationships.find(r => r.id === 'teammate')!.bond < 10 || s.team.cohesion < 10 || !s.npcs.some(n => s.team.memberIds.includes(n.id) && n.status === 'available'))) throw new Error('A equipe precisa de confiança, coesão e ao menos um aliado disponível.'); if (command.method === 'summon') { if (!c.summon || c.summon.bond < 3 || c.summon.favor < 1) throw new Error('O contrato precisa de vínculo e favor para atender em campo.'); c.summon.bond++; c.summon.favor--; } o.preparation = [...(o.preparation ?? []), command.method]; return note(s, 'preparation', `${command.method} altera recursos e riscos da operação.`); }
  if (command.type === 'MISSION_DECISION') { if (!s.offer) throw new Error('Não há missão pendente.'); s.offer.decision = command.decision; return note(s, 'decision', command.decision === 'protect' ? 'Prioridade definida: proteger pessoas e posição.' : command.decision === 'pursue' ? 'Prioridade definida: perseguir e capturar.' : 'Prioridade definida: negociar e extrair informação.'); }
  if (command.type === 'SET_COMBAT_PLAN') { if (!s.offer || s.combat) throw new Error('O plano só pode ser definido antes do combate.'); s.offer.plan = command.plan; return note(s, 'combat', `Plano de campo definido: ${command.plan}. Ele muda as condições da abertura, não apenas números.`); }
  if (command.type === 'WITHDRAW') { if (!s.offer) throw new Error('Não há oferta para retirar.'); if (s.combat) { s.combat.steps.push({ round: s.combat.round + 1, success: false, text: 'Você ordena retirada antes que a pressão destrua a operação.' }); return finishMission(s, 'withdrawn'); } s.offer = undefined; c.reputation--; return note(s, 'mission', 'Missão retirada antes do desdobramento; confiança da vila -1.'); }
  if (command.type === 'RUN_MISSION') return startCombat(s, content);
  if (command.type === 'FOCUS_DOJUTSU') { const combat = s.combat; if (!combat || !s.offer) throw new Error('O foco de linhagem só pode ser usado durante combate.'); if (!c.bloodline || !c.dojutsuActive || c.dojutsuStage < 1) throw new Error('O foco exige linhagem ativa no estágio 1.'); if (combat.ocularUsed) throw new Error('O foco de linhagem já foi gasto nesta operação.'); const cost = 4 + c.dojutsuStage * 2; if (combat.chakra < cost) throw new Error('Chakra insuficiente para sustentar o foco de linhagem.'); const effect = c.bloodline === 'lumen-eye' ? { advantage: 1, pressure: 0, text: 'Lumen Eye revela o fluxo ferido de chakra: uma abertura de suporte se torna visível.' } : c.bloodline === 'ashen-eye' ? { advantage: 2, pressure: 1, text: 'Ashen Eye força a visão além do limite: a abertura cresce, mas a pressão também.' } : c.bloodline === 'wood-release' ? { advantage: 1, pressure: -2, text: 'Mokuton ergue raízes de contenção e remove duas rotas da crise.' } : c.bloodline === 'ice-release' ? { advantage: 2, pressure: -1, text: 'Hyoton congela a passagem mais perigosa e devolve o ritmo à perseguição.' } : c.bloodline === 'crystal-release' ? { advantage: 1, pressure: -2, text: 'Shoton forma prismas de cobertura e quebra a linha de visão adversária.' } : c.bloodline === 'yin-yang-release' ? { advantage: 2, pressure: -1, text: 'Yin–Yang costura intenção e forma; uma ruptura deixa de escalar.' } : { advantage: 0, pressure: -2, text: 'Kurogane Eye lê o fio de intenção e fecha duas rotas antes que a armadilha se forme.' }; const steps = [...combat.steps]; steps[0] = { ...steps[0], text: `${steps[0].text} ${effect.text}` }; s.combat = { ...combat, chakra: combat.chakra - cost, advantage: combat.advantage + effect.advantage, pressure: Math.max(0, combat.pressure + effect.pressure), ocularUsed: true, steps }; c.dojutsuStrain += 2; return note(s, 'bloodline', `${effect.text} Foco de linhagem consome ${cost} chakra e adiciona strain.`); }
  if (command.type === 'CALL_SUMMON') { const combat = s.combat, summon = c.summon; if (!combat || !s.offer) throw new Error('A invocação de campo só pode ser chamada durante combate.'); if (!summon || summon.bond < 4 || summon.favor < 2) throw new Error('A invocação exige vínculo 4 e favor 2.'); if (combat.summonUsed) throw new Error('O contrato já interveio nesta operação.'); const effect = summon.id === 'corvid-contract' ? { advantage: 1, pressure: -1, exposure: 0, text: 'Corvos espalham a leitura do campo e entregam a rota que o inimigo escondia.' } : summon.id === 'hounds-contract' ? { advantage: s.offer.decision === 'pursue' ? 3 : 1, pressure: 0, exposure: 0, text: 'Cães de caça travam o rastro; fugir deixa de ser uma saída simples.' } : summon.id === 'moth-contract' ? { advantage: 0, pressure: -1, exposure: -1, text: 'Mariposas apagam linhas de visão e cobrem a retirada ou o resgate.' } : summon.id === 'boar-contract' ? { advantage: 1, pressure: -2, exposure: 0, text: 'Javalis quebram o terreno e erguem uma posição que o inimigo não pode ignorar.' } : { advantage: 0, pressure: -2, exposure: 0, text: 'Sapos exploram o terreno e devolvem uma abertura prática, não uma vitória gratuita.' }; const steps = [...combat.steps]; steps[0] = { ...steps[0], text: `${steps[0].text} ${effect.text}` }; summon.favor -= 2; summon.bond = Math.min(12, summon.bond + 1); s.combat = { ...combat, advantage: combat.advantage + effect.advantage, pressure: Math.max(0, combat.pressure + effect.pressure), exposure: Math.max(0, combat.exposure + effect.exposure), summonUsed: true, steps }; return note(s, 'summon', `${summon.name} atende ao campo: ${effect.text} Favor restante ${summon.favor}.`); }
  if (command.type === 'RESOLVE_COMBAT_BEAT') return resolveCombatBeat(s, command.approach, command.jutsuId, content);
  if (command.type === 'END_CAREER') { if (!['Chuunin', 'Jounin'].includes(c.rank)) throw new Error('Uma carreira só pode encerrar depois de alcançar Chuunin.'); return conclude(s, 'retired'); }
  return s;
}
