import { useEffect, useState } from 'react';
import rawContent from './data/core.json';
import { validateContent } from './domain/validate';
import type { Command, GameState } from './domain/types';
import { applyCommand, createGame } from './engine/simulation';
import { archiveLegacy, clearStoredGame, loadHall, loadStoredGame, storeGame, type HallEntry } from './engine/save';

const content = validateContent(rawContent);
const active = (rank: string) => ['Genin', 'Chuunin', 'Jounin'].includes(rank);
const statName: Record<string, string> = { ninjutsu: 'Ninjutsu', taijutsu: 'Taijutsu', genjutsu: 'Genjutsu', intelligence: 'Inteligência', strength: 'Força', speed: 'Velocidade', stamina: 'Stamina', handSeals: 'Selos', chakraControl: 'Controle de Chakra', willpower: 'Força de Vontade' };
const statTier = (value: number) => value >= 13 ? 'S+' : value >= 11 ? 'S' : value >= 9 ? 'A' : value >= 7 ? 'B' : value >= 5 ? 'C' : value >= 3 ? 'D' : 'E';
const careerName = { anbu: 'ANBU', sensei: 'Sensei', commander: 'Comando de Campo', rogue: 'Missing-nin' };
export default function App() {
  const [name, setName] = useState('Ren'); const [state, setState] = useState<GameState | null>(() => loadStoredGame()); const [message, setMessage] = useState(''); const [hall, setHall] = useState<HallEntry[]>(() => loadHall());
  useEffect(() => { if (state) { storeGame(state); if (state.legacy) { archiveLegacy(state); setHall(loadHall()); } } }, [state]);
  const begin = () => { setState(createGame(name, Date.now() >>> 0)); setMessage('Uma vida determinística começou; o mesmo seed e escolhas reproduzem a mesma crônica.'); };
  const run = (command: Command) => { if (!state) return; try { setState(applyCommand(state, command, content)); setMessage(''); } catch (e) { setMessage((e as Error).message); } };
  if (!state) return <main className="landing"><section><p className="eyebrow">SHINOBI CHRONICLE · CARREIRA</p><h1>Uma vida inteira de escolhas.</h1><p>Da Academia ao legado: missões, vínculos, reputação, decisões de campo e o momento de encerrar a própria história.</p><label>Nome<input value={name} onChange={e => setName(e.target.value)} maxLength={24} /></label><button className="primary" onClick={begin}>Começar vida</button>{hall.length > 0 && <div className="hall-preview"><h2>Hall of Legends</h2>{hall.slice(0, 3).map(entry => <p key={entry.seed}><b>{entry.name}</b> · {entry.title}</p>)}</div>}<small>Autosave local ativo. Retratos e arte usam slots substituíveis.</small></section></main>;
  const c = state.character, offer = state.offer, combat = state.combat, slots = c.rank === 'Genin' ? 3 : c.rank === 'Chuunin' ? 4 : c.rank === 'Jounin' ? 5 : 0;
  const replace = (slot: number, id: string) => { if (!c.knownJutsu.includes(id)) { setMessage('Aprenda essa técnica na biblioteca antes de equipá-la.'); return; } const next = [...c.loadout]; next[slot] = id; if (new Set(next).size === next.length) run({ type: 'SET_LOADOUT', jutsuIds: next }); };
  if (state.legacy) return <main className="legacy"><p className="eyebrow">HALL OF LEGENDS · VIDA CONCLUÍDA</p><h1>{state.legacy.title}</h1><p className="bio">{state.legacy.biography}</p><div className="legacy-grid"><section className="panel"><h2>Honras</h2>{state.legacy.honors.length ? state.legacy.honors.map(h => <p key={h}>◆ {h}</p>) : <p>Nenhuma honraria formal, mas uma história permanece.</p>}</section><section className="panel"><h2>Estatísticas de vida</h2><p>{state.legacy.stats.successes} sucessos em {state.legacy.stats.missions} missões</p><p>Maior missão: {state.legacy.stats.highestMission}</p><p>{state.legacy.stats.trainings} sessões de treino · {state.legacy.stats.daysServed} dias de carreira</p></section><section className="panel"><h2>Hall of Legends</h2>{hall.slice(0, 5).map(entry => <p key={entry.seed}><b>{entry.name}</b> · {entry.title}</p>)}</section></div><button className="primary" onClick={() => begin()}>Iniciar nova vida</button><button className="ghost" onClick={() => { clearStoredGame(); setState(null); }}>Voltar à abertura</button></main>;
  return <main><header><div><p className="eyebrow">DIA {c.day} · {c.village} · {Math.floor(c.day / 90) + 1}ª estação</p><h1>{c.name} <span>{c.rank}</span></h1><p className="hint">Traço: <b>{c.trait.name}</b> — {c.trait.description}</p></div><div className="resources"><b>{c.ryo} ryo</b><b>Saúde {c.health}</b><b>Chakra {c.chakraPool}/{c.attributes.stamina * 10 + c.attributes.chakraControl * 2}</b><b>Fadiga {c.fatigue}/14</b><b>Reputação {c.reputation}</b><b>Honra {c.honor}</b></div></header>
    {message && <p className="notice">{message}</p>}
    {active(c.rank) && <section className="panel rival-panel"><h2>Rivalidade: {state.rival.name}</h2><p><b>{state.rival.style}</b> · afinidade {state.rival.affinity} · estágio {state.rival.stage} · reputação {state.rival.reputation}</p><p className="hint">{state.rival.memory}. Rivalidade {state.rival.rivalry} · postura {state.rival.stance}.</p><button onClick={() => run({ type: 'RIVAL_ENCOUNTER', approach: 'challenge' })}>Aceitar desafio</button><button onClick={() => run({ type: 'RIVAL_ENCOUNTER', approach: 'study' })}>Estudar o contraponto</button><button onClick={() => run({ type: 'RIVAL_ENCOUNTER', approach: 'ally' })}>Propor aliança</button></section>}
    <div className="layout career-layout"><section className="panel"><h2>Ficha principal</h2><p className="hint">E 1–2 · D 3–4 · C 5–6 · B 7–8 · A 9–10 · S 11–12 · S+ 13+</p><div className="stats">{Object.entries(c.attributes).map(([key, value]) => <div key={key}><span>{statName[key]}</span><b>{value} <em>{statTier(value)}</em></b><button onClick={() => run({ type: 'TRAIN', attribute: key as keyof typeof c.attributes })}>treinar</button></div>)}</div>{c.injury && <p className="injury">{c.injury.name} · recuperação: {c.injury.days} dias</p>}<button onClick={() => run({ type: 'REST' })}>Recuperar 3 dias</button><button onClick={() => run({ type: 'ADVANCE_SEASON' })}>Avançar uma estação</button>
      {c.rank === 'Academy' && <><p className="hint">Graduação: Inteligência + Selos ≥ 8. Atual: {c.attributes.intelligence + c.attributes.handSeals}.</p><button className="primary" onClick={() => run({ type: 'GRADUATE' })}>Fazer prova de graduação</button></>}
      {c.rank === 'Genin' && <><p className="hint">Seu ciclo Genin: 2 sucessos liberam o Circuito Regional; Chuunin exige Circuito, 3 sucessos e reputação 4. Atual: {state.stats.successes} / {c.reputation}.</p>{!c.geninFieldMark && (state.regionalCircuit ? <article className="dilemma"><b>Circuito Regional · {state.regionalCircuit.host}</b><p>{state.regionalCircuit.prompt}</p><button onClick={() => run({ type: 'RESOLVE_REGIONAL_CIRCUIT', choice: 'shield' })}>Proteger a equipe</button><button onClick={() => run({ type: 'RESOLVE_REGIONAL_CIRCUIT', choice: 'trace' })}>Seguir o corredor</button><button onClick={() => run({ type: 'RESOLVE_REGIONAL_CIRCUIT', choice: 'parley' })}>Conter a acusação</button></article> : <button className="primary" onClick={() => run({ type: 'START_REGIONAL_CIRCUIT' })}>Entrar no Circuito Regional</button>)}{c.geninFieldMark && <p className="hint">Assinatura Genin: <b>{c.geninFieldMark === 'guardian' ? 'Guardião' : c.geninFieldMark === 'scout' ? 'Batedor' : 'Mediador'}</b>. Ela fortalece convites compatíveis, mas não bloqueia outros caminhos.</p>}{state.chuuninExam ? <article className="dilemma"><b>Exame Chuunin</b><p>{state.chuuninExam.prompt}</p><button onClick={() => run({ type: 'RESOLVE_CHUUNIN_EXAM', choice: 'rescue' })}>Salvar o mensageiro</button><button onClick={() => run({ type: 'RESOLVE_CHUUNIN_EXAM', choice: 'secure' })}>Proteger o pergaminho</button><button onClick={() => run({ type: 'RESOLVE_CHUUNIN_EXAM', choice: 'analyze' })}>Ler o observador</button></article> : <button className="primary" onClick={() => run({ type: 'PROMOTE' })}>Iniciar Exame Chuunin</button>}</>}
      {c.rank === 'Chuunin' && <><p className="hint">Jounin: 8 sucessos, reputação 12, atributos totais 32. Atual: {state.stats.successes} / {c.reputation} / {Object.values(c.attributes).reduce((a,b) => a+b,0)}.</p><button className="primary" onClick={() => run({ type: 'PROMOTE' })}>Solicitar avaliação Jounin</button><button className="ghost" onClick={() => run({ type: 'END_CAREER' })}>Encerrar carreira e registrar legado</button></>}
      {c.rank === 'Jounin' && <>{c.careerPath ? <p className="hint">Nomeação atual: <b>{careerName[c.careerPath]}</b>. Ela muda a forma de responder às crises e o legado possível.</p> : <article className="dilemma"><b>Nomeação de carreira — escolha permanente</b><p>ANBU: 12 sucessos, reputação 16, Inteligência + Vontade 11. Sensei: 10 sucessos, honra 10, vínculos 45. Comando: 12 sucessos, reputação 18, conselho 8.</p><button onClick={() => run({ type: 'CHOOSE_CAREER_PATH', path: 'anbu' })}>Aceitar máscara ANBU</button><button onClick={() => run({ type: 'CHOOSE_CAREER_PATH', path: 'sensei' })}>Assumir turma Sensei</button><button onClick={() => run({ type: 'CHOOSE_CAREER_PATH', path: 'commander' })}>Assumir Comando</button></article>}<button className="ghost" onClick={() => run({ type: 'END_CAREER' })}>Encerrar carreira e registrar legado</button></>}
    </section>
    <section className="panel"><h2>Build e caminhos</h2>{active(c.rank) ? <><p className="hint">Loadout de {slots} técnicas. A escolha muda a resposta tática; domínio cresce em campo.</p><div className="loadout">{content.jutsu.map(j => <div key={j.id} className={c.loadout.includes(j.id) ? 'selected' : ''}><b>{j.name}</b><small>{j.tags.join(' · ')} · domínio {c.mastery[j.id] ?? 0}</small><span>{j.description}</span><div>{Array.from({ length: slots }, (_, slot) => <button key={slot} disabled={c.loadout[slot] === j.id} onClick={() => replace(slot, j.id)}>slot {slot + 1}</button>)}</div></div>)}</div><div className="paths"><button disabled={!!c.specialization} onClick={() => run({ type: 'CHOOSE_PATH', kind: 'specialization', id: 'tracker' })}>Especializar: Tracker</button><button disabled={!!c.bloodline} onClick={() => run({ type: 'CHOOSE_PATH', kind: 'bloodline', id: 'kurogane-eye' })}>Despertar: Kurogane Eye</button><button disabled={!!c.summon} onClick={() => run({ type: 'CHOOSE_PATH', kind: 'summon', id: 'toad-contract' })}>Contrato de Sapo</button><button disabled={!!c.bijuu} onClick={() => run({ type: 'FORM_BIJUU_LINK', id: 'kurotsume' })}>Enfrentar selo: Kurotsume</button></div>{c.bloodline && <p><button onClick={() => run({ type: 'TOGGLE_DOJUTSU' })}>{c.dojutsuActive ? 'Desativar' : 'Ativar'} dōjutsu</button><button onClick={() => run({ type: 'CULTIVATE_DOJUTSU' })}>Meditar o olho</button> estágio {c.dojutsuStage} · insight {c.dojutsuInsight} · strain {c.dojutsuStrain}/7</p>}{c.bijuu && <div className="bijuu"><b>{c.bijuu.name}</b><small>Trust {c.bijuu.trust} · Respect {c.bijuu.respect} · Control {c.bijuu.control} · Sync {c.bijuu.synchronization} · Unrest {c.bijuu.unrest}</small><button onClick={() => run({ type: 'CULTIVATE_BIJUU', approach: 'cooperate' })}>Cooperar</button><button onClick={() => run({ type: 'CULTIVATE_BIJUU', approach: 'suppress' })}>Suprimir</button><button onClick={() => run({ type: 'CULTIVATE_BIJUU', approach: 'dominate' })}>Dominar</button><button className={c.bijuu.cloakActive ? 'chosen' : ''} onClick={() => run({ type: 'TOGGLE_CLOAK' })}>{c.bijuu.cloakActive ? 'Recolher capa' : 'Ativar capa'}</button></div>}{c.summon && <p><button onClick={() => run({ type: 'CULTIVATE_SUMMON' })}>Cumprir favor do contrato</button> {c.summon.name} · vínculo {c.summon.bond} · favor {c.summon.favor}</p>}<p className="hint">{c.specialization && 'Tracker amplia leitura de cenário. '}{c.bloodline && 'Dōjutsu adiciona percepção, mas acumula strain. '}</p></> : <p>Os caminhos de combate se abrem quando a carreira começa.</p>}</section>
    <section className="panel library"><h2>Biblioteca de jutsus</h2><p className="hint">Aprender e equipar são escolhas separadas. Técnica na biblioteca guarda domínio; técnica no deck entra em combate.</p>{content.jutsu.map(jutsu => <div key={jutsu.id}><b>{jutsu.name}</b><small>{c.knownJutsu.includes(jutsu.id) ? `aprendida · domínio ${c.mastery[jutsu.id] ?? 0}` : `custo de estudo ${15 + jutsu.chakraCost * 2 + (jutsu.requires?.length ?? 0) * 10} ryo`}{jutsu.requires?.length ? ` · exige ${jutsu.requires.map(id => content.jutsu.find(parent => parent.id === id)?.name).join(' + ')}` : ''}{jutsu.specialization ? ` · exige ${jutsu.specialization}` : ''}{jutsu.bloodline ? ` · exige linhagem ${content.bloodlines.find(path => path.id === jutsu.bloodline)?.name}` : ''}</small>{!c.knownJutsu.includes(jutsu.id) && <button onClick={() => run({ type: 'LEARN_JUTSU', id: jutsu.id })}>Aprender</button>}</div>)}</section>
    <section className="panel channels"><h2>Canais da build</h2><p><b>Jutsu base:</b> {c.loadout.length}/{slots || '—'} slots equipados</p><p><b>Doutrina:</b> {c.specialization ? content.specializations.find(path => path.id === c.specialization)?.name : 'sem especialização'} · não ocupa slot</p><p><b>Ocular:</b> {c.bloodline ? `${content.bloodlines.find(path => path.id === c.bloodline)?.name} · estágio ${c.dojutsuStage}` : 'nenhuma linhagem'} · canal próprio</p><p><b>Contrato:</b> {c.summon ? `${c.summon.name} · favor ${c.summon.favor}` : 'nenhuma invocação'} · canal de apoio</p><p><b>Bijuu:</b> {c.bijuu ? `${c.bijuu.name} · ${c.bijuu.mantleActive ? 'Manto Ressonante' : c.bijuu.cloakActive ? 'capa ativa' : 'selo estável'}` : 'nenhuma'} · canal interno</p><p><b>Modo:</b> Sage {c.modes.sageActive ? c.modes.sageForm : 'inativo'} · Portões {c.modes.openGates || 'fechados'} · canal de transformação</p><p><b>Logística:</b> antídoto {c.inventory.antidote} · placa {c.inventory['sealing-slate']} · recursos de preparação, não de jutsu</p></section>
    <section className="panel catalogue"><h2>Caminhos de build</h2><p className="hint">Cada vida escolhe uma especialização, uma linhagem ou Kekkei Genkai e um contrato. Isso mantém escolhas fortes e rejogáveis.</p><h3>Especialização</h3>{content.specializations.map(path => <button key={path.id} disabled={!!c.specialization} onClick={() => run({ type: 'CHOOSE_PATH', kind: 'specialization', id: path.id })}>{path.name}</button>)}<h3>Dōjutsu e Kekkei Genkai</h3>{content.bloodlines.map(path => <button key={path.id} disabled={!!c.bloodline} onClick={() => run({ type: 'CHOOSE_PATH', kind: 'bloodline', id: path.id })}>{path.name}</button>)}<h3>Contrato</h3>{content.summons.map(path => <button key={path.id} disabled={!!c.summon} onClick={() => run({ type: 'CHOOSE_PATH', kind: 'summon', id: path.id })}>{path.name}</button>)}</section>
    <section className="panel modes"><h2>Modos pessoais</h2><p>Insight Sage {c.modes.sageInsight}/8 · forma atual {c.modes.sageForm ?? 'nenhuma'} · treino dos Portões {c.modes.gateTraining}/6</p><button onClick={() => run({ type: 'CULTIVATE_SAGE' })}>Meditar energia natural</button><button className={c.modes.sageForm === 'stone' ? 'chosen' : ''} onClick={() => run({ type: 'ATTUNE_SAGE_FORM', form: 'stone' })}>Sintonizar Pedra</button><button className={c.modes.sageForm === 'storm' ? 'chosen' : ''} onClick={() => run({ type: 'ATTUNE_SAGE_FORM', form: 'storm' })}>Sintonizar Tempestade</button><button className={c.modes.sageForm === 'veil' ? 'chosen' : ''} onClick={() => run({ type: 'ATTUNE_SAGE_FORM', form: 'veil' })}>Sintonizar Véu</button><button className={c.modes.sageActive ? 'chosen' : ''} onClick={() => run({ type: 'TOGGLE_SAGE' })}>{c.modes.sageActive ? 'Dispersar Sage Mode' : 'Ativar Sage Mode'}</button><button onClick={() => run({ type: 'TRAIN_GATES' })}>Treinar Portões</button><button className={c.modes.openGates === 1 ? 'chosen' : ''} onClick={() => run({ type: 'OPEN_GATES', level: 1 })}>Abrir 1º Portão</button><button className={c.modes.openGates === 2 ? 'chosen' : ''} onClick={() => run({ type: 'OPEN_GATES', level: 2 })}>Abrir 2º Portão</button><button className={c.modes.openGates === 3 ? 'chosen' : ''} onClick={() => run({ type: 'OPEN_GATES', level: 3 })}>Abrir 3º Portão</button>{c.bijuu && <p><button className={c.bijuu.mantleActive ? 'chosen' : ''} onClick={() => run({ type: 'TOGGLE_MANTLE' })}>{c.bijuu.mantleActive ? 'Recuar Manto Ressonante' : 'Ativar Manto Ressonante'}</button></p>}<h3>Mentor: {c.mentor.name}</h3><p className="hint">{c.mentor.description} · vínculo {c.mentor.bond} · lições {c.mentor.lessons}/3</p><button onClick={() => run({ type: 'MENTOR_LESSON' })}>Pedir lição decisiva</button>{offer && !combat && <button onClick={() => run({ type: 'CONSULT_MENTOR' })}>Consultar mentor sobre a missão</button>}<p className="hint">Pedra acrescenta defesa/controle por 6 chakra; Tempestade, mobilidade/percepção por 10; Véu, furtividade/percepção por 12. O Manto amplia o chakra e o risco; Portões cobram saúde e fadiga depois do campo.</p></section>
    <section className="panel logistics"><h2>Logística e pesquisa</h2><p>Antídoto: {c.inventory.antidote} · Placa de selamento: {c.inventory['sealing-slate']}</p><div className="actions"><button onClick={() => run({ type: 'BUY_SUPPLY', item: 'antidote' })}>Comprar antídoto (18)</button><button onClick={() => run({ type: 'BUY_SUPPLY', item: 'sealing-slate' })}>Comprar placa (35)</button></div><p>Selamento {c.research.sealing}</p><button onClick={() => run({ type: 'RESEARCH', project: 'sealing' })}>Pesquisar selamento</button><p className="hint">Ferimentos se recuperam apenas com a passagem do tempo. Selamento amplia a preparação de missão e consome tempo e ryo.</p></section>
    <section className="panel mission">
      <h2>Missões e mundo</h2>
      <p className="factions">Vila {c.factionTrust.village} · Submundo {c.factionTrust.underworld} · Notoriedade {c.notoriety}</p>
      {!c.careerPath && ['Chuunin', 'Jounin'].includes(c.rank) && <details><summary>Caminho fora da vila</summary><p className="hint">Missing-nin exige notoriedade 7 ou confiança do submundo 7.</p><button onClick={() => run({ type: 'CHOOSE_CAREER_PATH', path: 'rogue' })}>Romper com a vila</button></details>}
      {!offer && active(c.rank) && <button className="primary" onClick={() => run({ type: 'OFFER_MISSION' })}>Consultar quadro de missões</button>}
      {offer && !combat && <>
        <p className="eyebrow">{offer.rank}-RANK · {offer.statedRisk}</p><h3>{offer.title}</h3><p>{offer.objective}</p><p className="intel">Inteligência: {offer.intel}</p><p className="dilemma"><b>Dilema:</b> {offer.dilemma}</p>
        <div className="actions"><button className={offer.decision === 'protect' ? 'chosen' : ''} onClick={() => run({ type: 'MISSION_DECISION', decision: 'protect' })}>Proteger</button><button className={offer.decision === 'pursue' ? 'chosen' : ''} onClick={() => run({ type: 'MISSION_DECISION', decision: 'pursue' })}>Perseguir</button><button className={offer.decision === 'negotiate' ? 'chosen' : ''} onClick={() => run({ type: 'MISSION_DECISION', decision: 'negotiate' })}>Negociar</button></div>
        <p>Recompensa anunciada: {offer.reward} ryo</p><button className="primary" onClick={() => run({ type: 'PREPARE_SMART' })}>Preparação recomendada</button>
        <details><summary>Preparar manualmente</summary><div className="actions"><button onClick={() => run({ type: 'PREPARE', method: 'intel' })}>Investigar</button><button onClick={() => run({ type: 'PREPARE', method: 'gear' })}>Equipamento (20)</button><button onClick={() => run({ type: 'PREPARE', method: 'seal' })}>Placa de selamento</button><button onClick={() => run({ type: 'PREPARE', method: 'rest' })}>Descansar</button><button onClick={() => run({ type: 'PREPARE', method: 'team' })}>Coordenar equipe</button>{c.summon && <button onClick={() => run({ type: 'PREPARE', method: 'summon' })}>Pedir ao contrato</button>}</div></details>
        <p className="hint">Plano de campo muda as condições da abertura.</p><div className="actions"><button className={offer.plan === 'infiltrate' ? 'chosen' : ''} onClick={() => run({ type: 'SET_COMBAT_PLAN', plan: 'infiltrate' })}>Infiltrar</button><button className={offer.plan === 'contain' ? 'chosen' : ''} onClick={() => run({ type: 'SET_COMBAT_PLAN', plan: 'contain' })}>Conter</button><button className={offer.plan === 'guard' ? 'chosen' : ''} onClick={() => run({ type: 'SET_COMBAT_PLAN', plan: 'guard' })}>Proteger linha</button><button className={offer.plan === 'pressure' ? 'chosen' : ''} onClick={() => run({ type: 'SET_COMBAT_PLAN', plan: 'pressure' })}>Pressionar</button></div>
        <button className="primary" disabled={!offer.decision || !offer.plan} onClick={() => run({ type: 'RUN_MISSION' })}>Iniciar combate simulado</button><button className="ghost" onClick={() => run({ type: 'WITHDRAW' })}>Retirar-se</button>
      </>}
      {combat && offer && <article className="combat">
        <p className="eyebrow">COMBATE SIMULADO · TROCA {combat.round + 1}/3</p><h3>{offer.title}</h3><p>Plano: {combat.plan} · Chakra disponível: {combat.chakra} · Pressão: {combat.pressure}</p><p className="dilemma">Escolha a técnica líder e a intenção. Outra técnica equipada entra automaticamente como continuidade se combinar com a troca e houver chakra; alterne o líder para rodar seu kit.</p>{c.dojutsuActive && c.dojutsuStage >= 1 && !combat.ocularUsed && <button className="primary" onClick={() => run({ type: 'FOCUS_DOJUTSU' })}>Focar técnica ocular</button>}{c.summon && !combat.summonUsed && <button className="primary" onClick={() => run({ type: 'CALL_SUMMON' })}>Chamar {c.summon.name}</button>}
        {c.loadout.map(id => { const jutsu = content.jutsu.find(item => item.id === id)!; const cooling = combat.leadHistory.at(-1) === id && c.loadout.length > 1; return <div className="combat-technique" key={id}><b>{jutsu.name}</b><small>{jutsu.tags.join(' · ')} · custo {jutsu.chakraCost}{cooling ? ' · em rotação' : ''}</small><div><button disabled={cooling} onClick={() => run({ type: 'RESOLVE_COMBAT_BEAT', approach: 'probe', jutsuId: id })}>Sondar</button><button disabled={cooling} onClick={() => run({ type: 'RESOLVE_COMBAT_BEAT', approach: 'commit', jutsuId: id })}>Comprometer</button><button disabled={cooling} onClick={() => run({ type: 'RESOLVE_COMBAT_BEAT', approach: 'protect', jutsuId: id })}>Proteger</button><button disabled={cooling} onClick={() => run({ type: 'RESOLVE_COMBAT_BEAT', approach: 'feint', jutsuId: id })}>Fintar</button></div></div>; })}
        <button className="ghost" onClick={() => run({ type: 'WITHDRAW' })}>Ordenar retirada</button>{combat.steps.map(step => <p key={step.round} className={step.success ? 'good' : 'bad'}><b>{step.round ? `Troca ${step.round}` : 'Abertura'}:</b> {step.text}</p>)}
      </article>}
      {state.lastReport && <article className="report"><h3>Relatório: {state.lastReport.rank} · {state.lastReport.outcome}</h3><p>Prioridade: {state.lastReport.decision}</p>{state.lastReport.steps.map(step => <p key={step.round} className={step.success ? 'good' : 'bad'}><b>{step.round ? `Troca ${step.round}` : 'Leitura'}:</b> {step.text}</p>)}</article>}
    </section>
    <section className="panel relationships"><h2>Pessoas, equipe e memória</h2>{c.relationships.map(r => <div key={r.id}><b>{r.name}</b><span>vínculo {r.bond}</span><small>{r.memory}</small><button onClick={() => run({ type: 'BUILD_RELATIONSHIP', id: r.id })}>dedicar 3 dias</button></div>)}<h3>Contatos persistentes</h3><p className="hint">Coesão da equipe: {state.team.cohesion}. Membros em campo: {state.team.memberIds.map(id => state.npcs.find(n => n.id === id)?.name).join(', ') || 'ninguém'}.</p>{state.npcs.map(n => <div key={n.id}><b>{n.name}</b><span>{n.status} · vínculo {n.bond} · arco {n.arcStage}/2</span><small>{n.goal}. {n.memory}</small><button onClick={() => run({ type: 'BUILD_NPC_BOND', id: n.id })}>conviver 3 dias</button>{n.role !== 'rival' && <button onClick={() => run({ type: 'TOGGLE_TEAM_MEMBER', id: n.id })}>{state.team.memberIds.includes(n.id) ? 'remover da equipe' : 'convidar para equipe'}</button>}</div>)}</section>
    <section className="panel world"><h2>Mundo e arcos</h2><p>Estação {state.world.season} · Tensão de fronteira {state.world.borderTension} · Conselho {state.world.councilTrust}</p><h3>Rumores</h3>{state.world.rumors.slice(-3).reverse().map((rumor, i) => <p key={i} className="hint">• {rumor}</p>)}{state.world.secrets.length > 0 && <><h3>Segredos conhecidos</h3>{state.world.secrets.map((secret, i) => <p key={i} className="good">◆ {secret}</p>)}</>}{state.narrative && <article className="dilemma"><b>Arco: {state.npcs.find(n => n.id === state.narrative?.npcId)?.name}</b><p>{state.narrative.prompt}</p><button onClick={() => run({ type: 'RESOLVE_NARRATIVE', choice: 'support' })}>Apoiar</button><button onClick={() => run({ type: 'RESOLVE_NARRATIVE', choice: 'challenge' })}>Contestar</button><button onClick={() => run({ type: 'RESOLVE_NARRATIVE', choice: 'expose' })}>Expor ao conselho</button></article>}</section>
    <aside className="panel chronicle"><h2>Crônica</h2>{state.chronicle.slice().reverse().slice(0, 14).map((e, i) => <p key={i}><b>Dia {e.day}</b> · {e.text}</p>)}</aside></div></main>;
}
